DECLARE
  V_EXESQL VARCHAR2(256);
BEGIN
  V_EXESQL := 'ALTER TABLE SCMDATA.T_ORDERCHANGE ADD OLDLOC VARCHAR2(4)';
  EXECUTE IMMEDIATE V_EXESQL;
  V_EXESQL := 'COMMENT ON COLUMN SCMDATA.T_ORDERCHANGE.OLDLOC IS ''旧收货仓库''';
  EXECUTE IMMEDIATE V_EXESQL;
  V_EXESQL := 'ALTER TABLE SCMDATA.T_ORDERED ADD SHO_ID VARCHAR2(8)';
  EXECUTE IMMEDIATE V_EXESQL;
  V_EXESQL := 'ALTER TABLE SCMDATA.T_ORDERED ADD SEND_BY_SUP NUMBER(1)';
  EXECUTE IMMEDIATE V_EXESQL;
  V_EXESQL := 'COMMENT ON COLUMN SCMDATA.T_ORDERED.ISFIRSTORDERED IS ''是否首单''';
  EXECUTE IMMEDIATE V_EXESQL;
  V_EXESQL := 'COMMENT ON COLUMN SCMDATA.T_ORDERED.DEAL_FOLLOWER IS ''跟单员''';
  EXECUTE IMMEDIATE V_EXESQL;
  V_EXESQL := 'COMMENT ON COLUMN SCMDATA.T_ORDERED.SHO_ID IS ''仓库''';
  EXECUTE IMMEDIATE V_EXESQL;
  V_EXESQL := 'COMMENT ON COLUMN SCMDATA.T_ORDERED.SEND_BY_SUP IS ''是否供应商代发：1是,0否''';
  EXECUTE IMMEDIATE V_EXESQL;
END;
/
