BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_supp_110_3'' AND ITEM_ID = ''a_supp_120''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[SUPPLIER_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_supp_110_3'' AND ITEM_ID = ''a_supp_120''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_supp_110_3'',,''a_supp_120'',q''[]'',q''[SUPPLIER_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_check_101_1_2'' AND ITEM_ID = ''a_check_101_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT 0,q''[]'',q''[PERSON_DETAILS_LINK]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_check_101_1_2'' AND ITEM_ID = ''a_check_101_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_check_101_1_2'',0,''a_check_101_1'',q''[]'',q''[PERSON_DETAILS_LINK]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_supp_120_1'' AND ITEM_ID = ''a_supp_120''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[SUPPLIER_COMPANY_NAME]'',1,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_supp_120_1'' AND ITEM_ID = ''a_supp_120''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_supp_120_1'',,''a_supp_120'',q''[]'',q''[SUPPLIER_COMPANY_NAME]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_coop_103_130'' AND ITEM_ID = ''a_coop_130''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[BE_ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_coop_103_130'' AND ITEM_ID = ''a_coop_130''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_coop_103_130'',,''a_coop_130'',q''[]'',q''[BE_ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_check_102''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_check_102''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_coop_150_0'',,''a_check_102'',q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_check_101_1_3'' AND ITEM_ID = ''a_check_101_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT 0,q''[]'',q''[MACHINE_DETAILS_LINK]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_check_101_1_3'' AND ITEM_ID = ''a_check_101_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_check_101_1_3'',0,''a_check_101_1'',q''[]'',q''[MACHINE_DETAILS_LINK]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_check_103_4_1'' AND ITEM_ID = ''a_check_103_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT 0,q''[]'',q''[PERSON_DETAILS_LINK]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_check_103_4_1'' AND ITEM_ID = ''a_check_103_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_check_103_4_1'',0,''a_check_103_4'',q''[]'',q''[PERSON_DETAILS_LINK]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_coop_131'' AND ITEM_ID = ''a_coop_130''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[ASK_RECORD_ID]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_coop_131'' AND ITEM_ID = ''a_coop_130''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_coop_131'',,''a_coop_130'',q''[]'',q''[ASK_RECORD_ID]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_check_103_6_1'' AND ITEM_ID = ''a_check_103_6''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT 0,q''[]'',q''[CONTROL_DETAILS_LINK]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_check_103_6_1'' AND ITEM_ID = ''a_check_103_6''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_check_103_6_1'',0,''a_check_103_6'',q''[]'',q''[CONTROL_DETAILS_LINK]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_check_101_1_5'' AND ITEM_ID = ''a_check_103_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT 0,q''[]'',q''[AR_COMPANY_NAME_N]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_check_101_1_5'' AND ITEM_ID = ''a_check_103_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_check_101_1_5'',0,''a_check_103_1'',q''[]'',q''[AR_COMPANY_NAME_N]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_check_101''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_check_101''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_coop_150_0'',,''a_check_101'',q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_check_103_5_1'' AND ITEM_ID = ''a_check_103_5''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT 0,q''[]'',q''[MACHINE_DETAILS_LINK]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_check_103_5_1'' AND ITEM_ID = ''a_check_103_5''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_check_103_5_1'',0,''a_check_103_5'',q''[]'',q''[MACHINE_DETAILS_LINK]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_check_101_1_5'' AND ITEM_ID = ''a_check_101_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT 0,q''[]'',q''[AR_COMPANY_NAME_N]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_check_101_1_5'' AND ITEM_ID = ''a_check_101_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_check_101_1_5'',0,''a_check_101_1'',q''[]'',q''[AR_COMPANY_NAME_N]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_check_102_3'' AND ITEM_ID = ''a_check_102''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[LOGN_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_check_102_3'' AND ITEM_ID = ''a_check_102''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_check_102_3'',,''a_check_102'',q''[]'',q''[LOGN_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_check_101_1_4'' AND ITEM_ID = ''a_check_101_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT 0,q''[]'',q''[CONTROL_DETAILS_LINK]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_check_101_1_4'' AND ITEM_ID = ''a_check_101_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_check_101_1_4'',0,''a_check_101_1'',q''[]'',q''[CONTROL_DETAILS_LINK]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_coop_150''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_coop_150''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_coop_150_0'',,''a_coop_150'',q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_supp_110_3'' AND ITEM_ID = ''a_supp_160''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[SUPPLIER_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_supp_110_3'' AND ITEM_ID = ''a_supp_160''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_supp_110_3'',,''a_supp_160'',q''[]'',q''[SUPPLIER_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

