--T_ASK_RECORD  合作申请记录表

CREATE TABLE SCMDATA.T_ASK_RECORD_BAK AS
        SELECT * FROM SCMDATA.T_ASK_RECORD;

COMMENT ON TABLE SCMDATA.T_ASK_RECORD_BAK IS '合作申请记录表';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.SUPPLIER_PRODUCT IS '产品图片附件地址';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.SUPPLIER_GATE IS '公司办公室附件地址';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.SUPPLIER_OFFICE IS '产品图片附件地址';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.SUPPLIER_SITE IS '生产现场附件地址';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.BRAND_TYPE IS '合作品牌/客户 类型';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COOPERATION_BRAND IS '合作品牌/客户';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.PRODUCT_LINK IS '生产环节';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COMPANY_ABBREVIATION IS '公司简称';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COMPANY_TYPE IS '公司类型--对应验厂COMPANY_MOLD';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.LEGAL_REPRESENTATIVE IS '法定代表人';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COMPANY_CONTACT_PHONE IS '公司联系人手机';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.BE_COMPANY_ID IS '被申请方企业ID';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COMPANY_PROVINCE IS '公司省';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COMPANY_CITY IS '公司市';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COMPANY_COUNTY IS '公司区';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COMPANY_ADDRESS IS '公司详细地址';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.ASK_DATE IS '申请时间';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.ASK_USER_ID IS '申请人ID';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.ASK_SAY IS '申请说明';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COOPERATION_TYPE IS '意向合作类型';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COOPERATION_CLASSIFICATION IS '意向合作分类';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COOPERATION_SUBCATEGORY IS '意向合作子类';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COOPERATION_MODEL IS '意向合作模式';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.PRODUCTION_MODE IS '意向生产模式';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.CERTIFICATE_FILE IS '营业执照附件地址';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.OTHER_FILE IS '更多附件地址（多个逗号隔开）';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.CREATE_ID IS '创建人ID';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.CREATE_DATE IS '创建时间';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.UPDATE_ID IS '修改人ID';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.UPDATE_DATE IS '修改时间';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.REMARKS IS '备注';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COOR_ASK_FLOW_STATUS IS '合作申请审批状态';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COLLECTION IS '收藏';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.ORIGIN IS '来源';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COMPANY_NAME IS '公司名称';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.SOCIAL_CREDIT_CODE IS '统一社会信用代码';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COOPERATION_STATEMENT IS '合作申请说明';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.SAPPLY_USER IS '供应商申请人';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.SAPPLY_PHONE IS '供应商申请人手机';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.ASK_RECORD_ID IS '主键';

COMMENT ON column SCMDATA.T_ASK_RECORD_BAK.COMPANY_ID IS '申请方企业ID';

--T_ASK_SCOPE  

CREATE TABLE SCMDATA.T_ASK_SCOPE_BAK AS
        SELECT * FROM SCMDATA.T_ASK_SCOPE;

COMMENT ON TABLE SCMDATA.T_ASK_RECORD_BAK IS '合作申请记录表';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.ASK_SCOPE_ID IS '合作意向范围ID';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.COMPANY_ID IS '企业id';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.OBJECT_ID IS '所属单据ID';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.OBJECT_TYPE IS '单据类型(HZ合作申请，CA验厂申请（与单据前缀相同）)';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.COOPERATION_TYPE IS '意向合作类型';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.COOPERATION_CLASSIFICATION IS '意向合作分类';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.COOPERATION_PRODUCT_CATE IS '意向生产类别';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.COOPERATION_SUBCATEGORY IS '意向合作子类';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.BE_COMPANY_ID IS '被申请方企业(同时是，定义企业字典的企业)';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.UPDATE_TIME IS '';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.UPDATE_ID IS '';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.CREATE_ID IS '';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.CREATE_TIME IS '';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.REMARKS IS '';

COMMENT ON column SCMDATA.T_ASK_SCOPE_BAK.PAUSE IS '禁用(默认0)';

--T_FACTORY_ASK  验厂申请表

CREATE TABLE SCMDATA.T_FACTORY_ASK_BAK AS
        SELECT * FROM SCMDATA.T_FACTORY_ASK;

COMMENT ON TABLE SCMDATA.T_FACTORY_ASK_BAK IS '验厂申请表';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.RELA_SUPPLIER_ID IS '关联供应商';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.MEMO IS '备注';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.PRODUCT_LINK IS '生产环节';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.WORKER_NUM IS '车位人数';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.MACHINE_NUM IS '织机台数';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.RESERVE_CAPACITY IS '预约产能占比';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.PRODUCT_EFFICIENCY IS '产能效率';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.WORK_HOURS_DAY IS '上班时数/天';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.BRAND_TYPE IS '合作品牌/客户 类型';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COOPERATION_BRAND IS '合作品牌/客户';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.PRODUCT_TYPE IS '生产类型';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.IS_URGENT IS '是否紧急';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.SUPPLIER_GATE IS '公司大门附件地址';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.SUPPLIER_OFFICE IS '公司办公室附件地址';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.SUPPLIER_SITE IS '生产现场附件地址';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.SUPPLIER_PRODUCT IS '产品图片附件地址';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.CERTIFICATE_FILE IS '营业执照';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COM_MANUFACTURER IS '生产工厂（舍弃）';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COMPANY_CONTACT_PHONE IS '公司联系电话';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COMPANY_MOLD IS '公司类型';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.LEGAL_REPRESENTATIVE IS '法定代表人';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COMPANY_ABBREVIATION IS '公司简称';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.FACTORY_ASK_ID IS '主键';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COMPANY_ID IS '公司编号';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.ASK_DATE IS '验厂申请日期';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.ASK_USER_ID IS '验厂申请人ID';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COMPANY_CITY IS '公司市';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COMPANY_PROVINCE IS '公司省';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COMPANY_COUNTY IS '公司区';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.ASK_ADDRESS IS '验厂地址';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.CONTACT_NAME IS '联系人';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.CONTACT_PHONE IS '联系人手机';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COMPANY_TYPE IS '需求公司类型';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COOPERATION_CLASSIFICATION IS '意向合作分类';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COOPERATION_SUBCATEGORY IS '意向合作子类';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COOPERATION_METHOD IS '意向合作方式';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COOPERATION_MODEL IS '意向合作模式';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.PRODUCTION_MODE IS '意向生产模式';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.ASK_SAY IS '验厂申请说明';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.ORIGIN IS '来源';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.CREATE_ID IS '创建人ID';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.CREATE_DATE IS '创建时间';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.UPDATE_ID IS '修改人ID';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.UPDATE_DATE IS '修改时间';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.REMARKS IS '备注';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.ASK_COMPANY_ID IS '验厂公司编号';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.ASK_RECORD_ID IS '合作申请id';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.FACTRORY_ASK_FLOW_STATUS IS '审核状态';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.FACTORY_ASK_TYPE IS '验厂类型（0不验厂，1内部验厂，2第三方验厂）';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COOPERATION_TYPE IS '意向合作方式类型';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COOPERATION_COMPANY_ID IS '合作公司id';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.ASK_USER_DEPT_ID IS '申请部门id';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COMPANY_ADDRESS IS '公司地址';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.FACTORY_NAME IS '工厂名称';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.ASK_FILES IS '验厂申请附件';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.COMPANY_NAME IS '被验厂公司名称';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.SOCIAL_CREDIT_CODE IS '统一社会信用代码';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.FACTORY_PROVINCE IS '工厂所在省';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.FACTORY_CITY IS '工厂所在市';

COMMENT ON column SCMDATA.T_FACTORY_ASK_BAK.FACTORY_COUNTY IS '工厂所在区';

--T_FACTORY_REPORT  验厂报告

CREATE TABLE SCMDATA.T_FACTORY_REPORT_BAK AS
        SELECT * FROM SCMDATA.T_FACTORY_REPORT;

COMMENT ON TABLE SCMDATA.T_FACTORY_REPORT_BAK IS '验厂报告';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.ADMIT_RESULT IS '准入结果(舍弃)';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.IS_TRIALORDER IS '是否试单';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.PRODUCT_LINE IS '生产线类型';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.PRODUCT_LINE_NUM IS '生产线数量';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.WORKER_NUM IS '车位人数';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.QUALITY_STEP IS '质量等级';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.PATTERN_CAP IS '打版能力';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.FABRIC_PURCHASE_CAP IS '面料采购能力';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.FABRIC_CHECK_CAP IS '面料检测能力';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.COST_STEP IS '成本等级';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_PERSON1 IS '验厂人员1';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_PERSON1_PHONE IS '验厂人员1联系电话';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_PERSON2 IS '验厂人员2';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_PERSON2_PHONE IS '验厂人员2联系电话';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CERTIFICATE_FILE IS '营业执照';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.SUPPLIER_GATE IS '公司大门附件地址';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.SUPPLIER_OFFICE IS '公司办公室附件地址';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.SUPPLIER_SITE IS '生产现场附件地址';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.SUPPLIER_PRODUCT IS '产品图片附件地址';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.FACTORY_RESULT_SUGGEST IS '验厂结果建议';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.TRIALORDER_TYPE IS '试单模式';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.AUDIT_COMMENT IS '审核建议';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.RESERVE_CAPACITY IS '预约产能占比';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.PRODUCT_EFFICIENCY IS '产能效率';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.WORK_HOURS_DAY IS '上班时数/天';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.MACHINE_NUM IS '织机台数';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.FACTORY_REPORT_ID IS '主键';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.COMPANY_ID IS '公司ID';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.FACTORY_ASK_ID IS '验厂申请ID';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.COMPANY_CODE IS '验厂企业编号';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_USER_ID IS '验厂人员编号';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_DATE IS '验厂日期';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_METHOD IS '验厂方式';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_PROVINCE IS '验厂地址省';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_CITY IS '验厂地址市';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_COUNTY IS '验厂地址区';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_ADDRESS IS '验厂地址详细地址';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.COOPERATION_METHOD IS '合作方式';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.COOPERATION_MODEL IS '合作模式';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.PRODUCTION_MODE IS '生产模式';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.COOPERATION_TYPE IS '合作类型';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.COOPERATION_CLASSIFICATION IS '合作分类';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.COOPERATION_SUBCATEGORY IS '合作子类';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_REPORT_FILE IS '上传验厂报告';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_SAY IS '验厂评语';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CHECK_RESULT IS '验厂结论';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CREATE_ID IS '创建人ID';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.CREATE_DATE IS '创建时间';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.UPDATE_ID IS '修改人ID';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.UPDATE_DATE IS '修改时间';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.REMARKS IS '备注';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.REVIEW_DATE IS '审核时间';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.REVIEW_ID IS '审核人id';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.COMPANY_ADDRESS IS '公司地址';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.FACTORY_NAME IS '工厂名称';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.ASK_FILES IS '验厂申请附件';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_BAK.COMPANY_NAME IS '公司名称';

--T_FACTORY_REPORT_ABILITY  能力评估报告

CREATE TABLE SCMDATA.T_FACTORY_REPORT_ABILITY_BAK AS
        SELECT * FROM SCMDATA.T_FACTORY_REPORT_ABILITY;

COMMENT ON TABLE SCMDATA.T_FACTORY_REPORT_ABILITY_BAK IS '能力评估报告';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.INCOMPATIBLE_REASON IS '不符合原因';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.FACTORY_REPORT_ABILITY_ID IS '主键';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.COMPANY_ID IS '企业编码';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.FACTORY_REPORT_ID IS '验厂报告ID';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.COOPERATION_CLASSIFICATION IS '合作分类';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.COOPERATION_SUBCATEGORY IS '合作子类';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.ORIGINAL_DESIGN IS '原创设计';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.DEVELOPMENT_PROOFING IS '开发打样';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.MATERIALS_PROCUREMENT IS '物料采购';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.PRODUCTION_PROCESSING IS '生产加工';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.REMARKS IS '备注';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.COOPERATION_TYPE IS '合作类型';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.COOPERATION_PRODUCT_CATE IS '合作生产分类';

COMMENT ON column SCMDATA.T_FACTORY_REPORT_ABILITY_BAK.ABILITY_RESULT IS '能力评估结果';

--T_SUPPLIER_INFO  供应商档案

CREATE TABLE SCMDATA.T_SUPPLIER_INFO_BAK AS
        SELECT * FROM SCMDATA.T_SUPPLIER_INFO;

COMMENT ON TABLE SCMDATA.T_SUPPLIER_INFO_BAK IS '供应商档案';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COOP_POSITION IS '合作定位';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PRODUCT_LINE IS '生产线类型';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PRODUCT_LINE_NUM IS '生产线数量';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.WORKER_NUM IS '车位人数';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.MACHINE_NUM IS '织机台数';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.QUALITY_STEP IS '质量等级';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PATTERN_CAP IS '打版能力';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.FABRIC_PURCHASE_CAP IS '面料采购能力';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.FABRIC_CHECK_CAP IS '面料检测能力';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COST_STEP IS '成本等级';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.BRAND_TYPE IS '合作品牌/客户 类型';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PRODUCT_TYPE IS '生产类型';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PRODUCT_LINK IS '生产环节';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.FA_CONTACT_NAME IS '业务联系人';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.FA_CONTACT_PHONE IS '业务联系人手机';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COOPERATION_BRAND IS '合作品牌/客户';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_GATE IS '公司大门附件地址';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_OFFICE IS '公司办公室附件地址';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_PRODUCT IS '产品图片附件地址';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.FILE_REMARK IS '附件备注';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.RESERVE_CAPACITY IS '预约产能占比';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PRODUCT_EFFICIENCY IS '产能效率';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.WORK_HOURS_DAY IS '上班时数/天';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_SITE IS '生产现场附件地址';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COOP_STATE IS '合作状态';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PUBLISH_ID IS '发布人（接口）';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PUBLISH_DATE IS '发布时间（接口）';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PERSONAL_ACCOUNT IS '个人账号';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PERSONAL_PAYMENT IS '个人收款人';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PERSONAL_BANK IS '个人开户行';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PERSONAL_IDCARD IS '个人身份证号';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PERSONAL_PHONE IS '个人联系电话';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PAY_TYPE IS '付款方式';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SETTLEMENT_TYPE IS '结算方式';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.RECONCILIATION_USER IS '对账联系人';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.RECONCILIATION_PHONE IS '对账联系电话';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_INFO_ORIGIN IS '来源';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PAUSE IS '状态';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.CREATE_ID IS '创建人ID';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.CREATE_DATE IS '创建时间';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.UPDATE_ID IS '修改人ID';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.UPDATE_DATE IS '修改时间';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.REMARKS IS '备注';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_INFO_ORIGIN_ID IS '来源ID';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.STATUS IS '建档状态';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.CONTRACT_START_DATE IS '合同有效期从(作废)';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.CREATE_SUPP_DATE IS '建档日期';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_ADDRESS IS '公司地址';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.BIND_STATUS IS '绑定状态';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_CITY IS '公司市';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_PROVINCE IS '公司省';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_COUNTY IS '公司区';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.AREA_GROUP_LEADER IS '区域组长';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_INFO_ID IS '主键';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_ID IS '公司编码';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_CODE IS '供应商编号';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.INSIDE_SUPPLIER_CODE IS '内部供应商编号';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_COMPANY_ID IS '供应商在平台的企业id';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_COMPANY_ABBREVIATION IS '公司简称';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SUPPLIER_COMPANY_NAME IS '公司名称';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.LEGAL_REPRESENTATIVE IS '法定代表人';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_CREATE_DATE IS '成立日期';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.REGIST_ADDRESS IS '注册地址';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.CERTIFICATE_VALIDITY_START IS '营业执照开始有效期';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.CERTIFICATE_VALIDITY_END IS '营业执照截止有效期';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.REGIST_PRICE IS '注册资本';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SOCIAL_CREDIT_CODE IS '统一社会信用证件代码';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_TYPE IS '公司类型';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_PERSON IS '公司员工总人数';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_CONTACT_PERSON IS '公司联系人';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_CONTACT_PHONE IS '公司联系人手机';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.TAXPAYER IS '纳税人身份';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COMPANY_SAY IS '公司简介';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.CERTIFICATE_FILE IS '上传营业执照';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.ORGANIZATION_FILE IS '上传组织架构图';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.CONTRACT_STOP_DATE IS '合同有效期至（作废）';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.CONTRACT_FILE IS '上传合同附件（作废）';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COOPERATION_METHOD IS '合作方式';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COOPERATION_MODEL IS '合作模式';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PRODUCTION_MODE IS '生产模式';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COOPERATION_TYPE IS '合作类型';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COOPERATION_CLASSIFICATION IS '合作分类';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.COOPERATION_SUBCATEGORY IS '合作子类';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.SHARING_TYPE IS '共享类型';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PUBLIC_ACCOUNTS IS '对公账号';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PUBLIC_PAYMENT IS '对公收款人';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PUBLIC_BANK IS '对公开户行';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PUBLIC_ID IS '对公身份证号';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.PUBLIC_PHONE IS '对公联系电话';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.GROUP_NAME IS '分组名称';

COMMENT ON column SCMDATA.T_SUPPLIER_INFO_BAK.GENDAN_PERID IS '跟单员ID';

--T_SUPPLIER_SHARED  能力共享表

CREATE TABLE SCMDATA.T_SUPPLIER_SHARED_BAK AS
        SELECT * FROM SCMDATA.T_SUPPLIER_SHARED;

COMMENT ON TABLE SCMDATA.T_SUPPLIER_SHARED_BAK IS '能力共享表';

COMMENT ON column SCMDATA.T_SUPPLIER_SHARED_BAK.SUPPLIER_SHARED_ID IS '主键';

COMMENT ON column SCMDATA.T_SUPPLIER_SHARED_BAK.COMPANY_ID IS '企业编码';

COMMENT ON column SCMDATA.T_SUPPLIER_SHARED_BAK.SUPPLIER_INFO_ID IS '供应商档案ID';

COMMENT ON column SCMDATA.T_SUPPLIER_SHARED_BAK.SHARED_SUPPLIER_CODE IS '关联供应商的档案编号';

COMMENT ON column SCMDATA.T_SUPPLIER_SHARED_BAK.REMARKS IS '备注';

COMMENT ON column SCMDATA.T_SUPPLIER_SHARED_BAK.COOP_SCOPE_ID IS '合作范围ID';

--T_COOP_SCOPE  

CREATE TABLE SCMDATA.T_COOP_SCOPE_BAK AS
        SELECT * FROM SCMDATA.T_COOP_SCOPE;

COMMENT ON TABLE SCMDATA.T_SUPPLIER_SHARED_BAK IS '能力共享表';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.COOP_STATE IS '合作状态';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.SHARING_TYPE IS '共享类型';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.PUBLISH_ID IS '发布人（接口）';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.PUBLISH_DATE IS '发布时间（接口）';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.COOP_SCOPE_ID IS '合作范围编号（主键）';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.SUPPLIER_INFO_ID IS '供应商档案编号';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.COMPANY_ID IS '企业编号';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.COOP_MODE IS '合作模式';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.COOP_CLASSIFICATION IS '合作分类';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.COOP_PRODUCT_CATE IS '生产类别';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.COOP_SUBCATEGORY IS '合作产品子类';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.CREATE_ID IS '创建人';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.CREATE_TIME IS '创建时间';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.UPDATE_ID IS '修改人';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.UPDATE_TIME IS '修改时间';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.REMARKS IS '备注';

COMMENT ON column SCMDATA.T_COOP_SCOPE_BAK.PAUSE IS '禁用';

--T_FACTORY_ASK_OPER_LOG  验厂申请审核记录

CREATE TABLE SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK AS
        SELECT * FROM SCMDATA.T_FACTORY_ASK_OPER_LOG;

COMMENT ON TABLE SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK IS '验厂申请审核记录';

COMMENT ON column SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK.LOG_ID IS '主键';

COMMENT ON column SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK.FACTORY_ASK_ID IS '验厂申请单id';

COMMENT ON column SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK.OPER_USER_ID IS '操作用户';

COMMENT ON column SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK.OPER_CODE IS '操作方式字典编码(SUBMIT提交、AGREE同意、BACK驳回、DISAGREE不同意、CANCEL撤回）';

COMMENT ON column SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK.STATUS_AF_OPER IS '操作后表单的状态';

COMMENT ON column SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK.REMARKS IS '备注';

COMMENT ON column SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK.ASK_RECORD_ID IS '合作申请单id';

COMMENT ON column SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK.OPER_TIME IS '操作时间';

COMMENT ON column SCMDATA.T_FACTORY_ASK_OPER_LOG_BAK.OPER_USER_COMPANY_ID IS '操作公司';

--T_CONTRACT_INFO  合同信息

CREATE TABLE SCMDATA.T_CONTRACT_INFO_BAK AS
        SELECT * FROM SCMDATA.T_CONTRACT_INFO;

COMMENT ON TABLE SCMDATA.T_CONTRACT_INFO_BAK IS '合同信息';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.CHANGE_ID IS '更改人ID';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.CHANGE_TIME IS '更改时间';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.OPERATOR_ID IS '操作人ID';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.OPERATE_TIME IS '操作时间';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.CONTRACT_NUM IS '合同份数';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.CONTRACT_TYPE IS '合同类型';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.CONTRACT_INFO_ID IS '合同编号(主键)';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.SUPPLIER_INFO_ID IS '供应商档案编号（外键）';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.COMPANY_ID IS '公司编号（外键）';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.CONTRACT_START_DATE IS '开始日期';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.CONTRACT_STOP_DATE IS '结束日期';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.CONTRACT_SIGN_DATE IS '签订日期';

COMMENT ON column SCMDATA.T_CONTRACT_INFO_BAK.CONTRACT_FILE IS '附件';

--T_SUPPLIER_TYPE  企业合作类型显示表

CREATE TABLE SCMDATA.T_SUPPLIER_TYPE_BAK AS
        SELECT * FROM SCMDATA.T_SUPPLIER_TYPE;

COMMENT ON TABLE SCMDATA.T_SUPPLIER_TYPE_BAK IS '企业合作类型显示表';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.SUPPLIER_TYPE_ID IS '主键';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.COMPANY_ID IS '企业编码';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.SUPPLIER_TYPE_CODE IS '编码';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.SUPPLIER_TYPE_NAME IS '名称';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.IS_SUPPLIER_TYPE_OPEN IS '是否开放';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.PAUSE IS '状态';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.CREATE_ID IS '创建人ID';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.CREATE_TIME IS '创建时间';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.UPDATE_ID IS '修改人ID';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.UPDATE_TIME IS '修改时间';

COMMENT ON column SCMDATA.T_SUPPLIER_TYPE_BAK.REMARKS IS '备注';

