BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[SELECT t1.group_dict_value SHARING_TYPE,
       t1.group_dict_name  SHARING_TYPE_SP
  FROM scmdata.sys_group_dict t, scmdata.sys_group_dict t1
 WHERE t.group_dict_id = t1.parent_id
   AND t.group_dict_value = 'SHARE_METHOD'
   AND t1.pause = 0
ORDER BY t1.group_dict_value]';
  CV2 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_LOOK_UP WHERE ELEMENT_ID = ''lookup_a_supp_111_9''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_LOOK_UP SET (BEFORE_FIELD,DATA_TYPE,DISABLED_FIELD,FIELD_NAME,GROUP_FIELD,ICON,KEY_FIELD,MULTI_VALUE_FLAG,PORT_ID,RESULT_FIELD,SEARCH_FLAG,VALUE_SEP,LOOK_UP_SQL,PORT_SQL) = (SELECT q''[SHARING_TYPE]'',q''[1]'',q''[]'',q''[SHARING_TYPE_SP]'',q''[]'',q''[]'',q''[SHARING_TYPE]'',,q''[]'',q''[SHARING_TYPE_SP]'',,q''[]'',:CV1,:CV2 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_supp_111_9''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1,CV2;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_LOOK_UP (BEFORE_FIELD,DATA_TYPE,DISABLED_FIELD,ELEMENT_ID,FIELD_NAME,GROUP_FIELD,ICON,KEY_FIELD,MULTI_VALUE_FLAG,PORT_ID,RESULT_FIELD,SEARCH_FLAG,VALUE_SEP,LOOK_UP_SQL,PORT_SQL) SELECT q''[SHARING_TYPE]'',q''[1]'',q''[]'',''lookup_a_supp_111_9'',q''[SHARING_TYPE_SP]'',q''[]'',q''[]'',q''[SHARING_TYPE]'',,q''[]'',q''[SHARING_TYPE_SP]'',,q''[]'',:CV1,:CV2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1,CV2;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[SELECT t1.group_dict_value coop_mode,
       t1.group_dict_name  coop_mode_sp
  FROM scmdata.sys_group_dict t, scmdata.sys_group_dict t1
 WHERE t.group_dict_id = t1.parent_id
   AND t.group_dict_value = 'SUPPLY_TYPE'
   AND t1.pause = 0
 ORDER BY t1.group_dict_value]';
  CV2 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_LOOK_UP WHERE ELEMENT_ID = ''look_a_supp_151_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_LOOK_UP SET (BEFORE_FIELD,DATA_TYPE,DISABLED_FIELD,FIELD_NAME,GROUP_FIELD,ICON,KEY_FIELD,MULTI_VALUE_FLAG,PORT_ID,RESULT_FIELD,SEARCH_FLAG,VALUE_SEP,LOOK_UP_SQL,PORT_SQL) = (SELECT q''[COOP_MODE]'',q''[1]'',q''[]'',q''[COOP_MODE_SP]'',q''[]'',q''[]'',q''[COOP_MODE]'',,q''[]'',q''[COOP_MODE_SP]'',,q''[]'',:CV1,:CV2 FROM DUAL) WHERE ELEMENT_ID = ''look_a_supp_151_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1,CV2;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_LOOK_UP (BEFORE_FIELD,DATA_TYPE,DISABLED_FIELD,ELEMENT_ID,FIELD_NAME,GROUP_FIELD,ICON,KEY_FIELD,MULTI_VALUE_FLAG,PORT_ID,RESULT_FIELD,SEARCH_FLAG,VALUE_SEP,LOOK_UP_SQL,PORT_SQL) SELECT q''[COOP_MODE]'',q''[1]'',q''[]'',''look_a_supp_151_1'',q''[COOP_MODE_SP]'',q''[]'',q''[]'',q''[COOP_MODE]'',,q''[]'',q''[COOP_MODE_SP]'',,q''[]'',:CV1,:CV2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1,CV2;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[{DECLARE
  v_sql CLOB;
BEGIN
  v_sql := pkg_supplier_info.f_query_coop_status_looksql(p_coop_status_field => 'COOP_STATE',
                                                         p_suffix            => '_DESC');
 @StrResult := v_sql;
END;}]';
  CV2 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_LOOK_UP WHERE ELEMENT_ID = ''look_a_supp_111_7''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_LOOK_UP SET (BEFORE_FIELD,DATA_TYPE,DISABLED_FIELD,FIELD_NAME,GROUP_FIELD,ICON,KEY_FIELD,MULTI_VALUE_FLAG,PORT_ID,RESULT_FIELD,SEARCH_FLAG,VALUE_SEP,LOOK_UP_SQL,PORT_SQL) = (SELECT q''[COOP_STATE]'',q''[1]'',q''[]'',q''[COOP_STATE_DESC]'',q''[]'',q''[]'',q''[COOP_STATE]'',,q''[]'',q''[COOP_STATE_DESC]'',,q''[]'',:CV1,:CV2 FROM DUAL) WHERE ELEMENT_ID = ''look_a_supp_111_7''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1,CV2;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_LOOK_UP (BEFORE_FIELD,DATA_TYPE,DISABLED_FIELD,ELEMENT_ID,FIELD_NAME,GROUP_FIELD,ICON,KEY_FIELD,MULTI_VALUE_FLAG,PORT_ID,RESULT_FIELD,SEARCH_FLAG,VALUE_SEP,LOOK_UP_SQL,PORT_SQL) SELECT q''[COOP_STATE]'',q''[1]'',q''[]'',''look_a_supp_111_7'',q''[COOP_STATE_DESC]'',q''[]'',q''[]'',q''[COOP_STATE]'',,q''[]'',q''[COOP_STATE_DESC]'',,q''[]'',:CV1,:CV2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1,CV2;
     END IF;
  END;
END;
/

