BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_c_2420_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_c_2420_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_c_2420_1'',q''[action]'',,,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_c_2421_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_c_2421_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_c_2421_1'',q''[action]'',,,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_c_2431_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_c_2431_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_c_2431_2'',q''[pick]'',,,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_c_2440_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[scm_nbw]'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_c_2440_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[scm_nbw]'',''pick_c_2440_1'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''look_c_2431_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''look_c_2431_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''look_c_2431_1'',q''[lookup]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_c_2421_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_c_2421_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_c_2421_1'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_c_2411_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_c_2411_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_c_2411_1'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_c_2431_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_c_2431_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_c_2431_3'',q''[pick]'',,,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_c_2431_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_c_2431_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_c_2431_4'',q''[pick]'',,,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_c_2431_5''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_c_2431_5''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_c_2431_5'',q''[pick]'',,,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_c_2431_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_c_2431_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_c_2431_1'',q''[pick]'',,,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

