BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[{DECLARE v_sql CLOB;
  BEGIN
    v_sql := pkg_data_privs.get_look_up_sql(p_dict_type  => 'COMPANY_STORE_TYPE',
                                            p_key        => 'COMPANY_STORE_TYPE_DESC',
                                            p_value      => 'COL_11');

    @strresult := v_sql;

  END;}]';
  CV2 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_LOOK_UP WHERE ELEMENT_ID = ''look_c_2431_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_LOOK_UP SET (BEFORE_FIELD,DATA_TYPE,DISABLED_FIELD,FIELD_NAME,GROUP_FIELD,ICON,KEY_FIELD,MULTI_VALUE_FLAG,PORT_ID,RESULT_FIELD,SEARCH_FLAG,VALUE_SEP,LOOK_UP_SQL,PORT_SQL) = (SELECT q''[COL_11]'',q''[1]'',q''[0]'',q''[COMPANY_STORE_TYPE_DESC]'',q''[]'',q''[]'',q''[COL_11]'',0,q''[]'',q''[COMPANY_STORE_TYPE_DESC]'',0,q''[]'',:CV1,:CV2 FROM DUAL) WHERE ELEMENT_ID = ''look_c_2431_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1,CV2;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_LOOK_UP (BEFORE_FIELD,DATA_TYPE,DISABLED_FIELD,ELEMENT_ID,FIELD_NAME,GROUP_FIELD,ICON,KEY_FIELD,MULTI_VALUE_FLAG,PORT_ID,RESULT_FIELD,SEARCH_FLAG,VALUE_SEP,LOOK_UP_SQL,PORT_SQL) SELECT q''[COL_11]'',q''[1]'',q''[0]'',''look_c_2431_1'',q''[COMPANY_STORE_TYPE_DESC]'',q''[]'',q''[]'',q''[COL_11]'',0,q''[]'',q''[COMPANY_STORE_TYPE_DESC]'',0,q''[]'',:CV1,:CV2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1,CV2;
     END IF;
  END;
END;
/

