BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''assign_a_coop_162''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[assign]'',,,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''assign_a_coop_162''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''assign_a_coop_162'',q''[assign]'',,,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''assign_a_coop_162_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[assign]'',,,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''assign_a_coop_162_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''assign_a_coop_162_1'',q''[assign]'',,,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''look_a_coop_160_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''look_a_coop_160_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''look_a_coop_160_1'',q''[lookup]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_coop_161_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_coop_161_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_coop_161_1'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_coop_161_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_coop_161_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_coop_161_2'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''fc_a_coop_162''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''fc_a_coop_162''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''fc_a_coop_162'',q''[action]'',,,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_coop_162_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_coop_162_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_coop_162_1'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_coop_162_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_coop_162_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_coop_162_2'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_coop_160_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_coop_160_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_coop_160_1'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_coop_160_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_coop_160_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_coop_160_2'',q''[action]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_coop_161_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_coop_161_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_coop_161_1'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_coop_162_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_coop_162_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_coop_162_1'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_coop_162_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_coop_162_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_coop_162_2'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_coop_161_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_coop_161_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_coop_161_3'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_coop_161_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_coop_161_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,ENABLE_STAND_PERMISSION,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_coop_161_2'',q''[pick]'',,,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

