CREATE OR REPLACE FUNCTION SCMDATA.F_FORM_URL_ENCODE(DATA    IN VARCHAR2,
                                                     CHARSET IN VARCHAR2)
  RETURN VARCHAR2 AS
BEGIN
	--URL转化
  RETURN UTL_URL.ESCAPE(DATA, TRUE, CHARSET);
END;
/

