BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^SELECT (SELECT LOGN_NAME
          FROM SCMDATA.SYS_COMPANY
         WHERE COMPANY_ID = ASK_COMPANY_ID) CHECK_COMPANY_NAME,
       (SELECT NICK_NAME
          FROM SCMDATA.SYS_USER
         WHERE USER_ID = %CURRENT_USERID%) CHECK_USERNAME,
       (SELECT PHONE FROM SCMDATA.SYS_USER WHERE USER_ID = %CURRENT_USERID%) CHECKAPPLY_PHONE
  FROM SCMDATA.T_FACTORY_ASK
 WHERE FACTORY_ASK_ID = :FACTORY_ASK_ID^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_DEFAULT WHERE ELEMENT_ID = ''default_a_check_101_1_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_DEFAULT SET (DEFAULT_SQL) = (SELECT :CV1 FROM DUAL) WHERE ELEMENT_ID = ''default_a_check_101_1_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_DEFAULT (ELEMENT_ID,DEFAULT_SQL) SELECT :CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^select pkg_personal.F_show_username_by_company(u.user_id,
                                               %default_company_id%) ask_user_name,
       u.phone ask_user_phone,
       (select licence_num
          from sys_company
         where company_id = %default_company_id%) SOCIAL_CREDIT_CODE,
       (select logn_name
          from sys_company
         where company_id = %default_company_id%) ASK_COMPANY_NAME,
       '成品供应商' cooperation_type_desc,
       'PRODUCT_TYPE' cooperation_type
  from sys_user u
 where u.user_id = :user_id^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_DEFAULT WHERE ELEMENT_ID = ''default_a_coop_121''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_DEFAULT SET (DEFAULT_SQL) = (SELECT :CV1 FROM DUAL) WHERE ELEMENT_ID = ''default_a_coop_121''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_DEFAULT (ELEMENT_ID,DEFAULT_SQL) SELECT :CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^SELECT COOPERATION_TYPE,
       (SELECT LISTAGG(B.GROUP_DICT_NAME, ';')
          FROM (SELECT DISTINCT COOPERATION_TYPE TMP
                  FROM SCMDATA.T_ASK_SCOPE
                 WHERE OBJECT_ID = :ASK_RECORD_ID) A
         INNER JOIN SCMDATA.SYS_GROUP_DICT B
            ON A.TMP = B.GROUP_DICT_VALUE
           AND B.GROUP_DICT_TYPE = 'COOPERATION_TYPE') COOPERATION_TYPE_DESC,
       COOPERATION_CLASSIFICATION,
       (SELECT LISTAGG(B.GROUP_DICT_NAME, ';')
          FROM (SELECT DISTINCT COOPERATION_CLASSIFICATION TMP
                  FROM SCMDATA.T_ASK_SCOPE
                 WHERE OBJECT_ID = :ASK_RECORD_ID) A
         INNER JOIN SCMDATA.SYS_GROUP_DICT B
            ON A.TMP = B.GROUP_DICT_VALUE
           AND B.GROUP_DICT_TYPE = 'PRODUCT_TYPE') COOPERATION_CLASSIFICATION_DES,
       COOPERATION_PRODUCT_CATE,
       (SELECT LISTAGG(B.GROUP_DICT_NAME, ';')
          FROM (SELECT DISTINCT COOPERATION_PRODUCT_CATE TMP
                  FROM SCMDATA.T_ASK_SCOPE
                 WHERE OBJECT_ID = :ASK_RECORD_ID) A
         INNER JOIN SCMDATA.SYS_GROUP_DICT B
            ON A.TMP = B.GROUP_DICT_VALUE
           AND B.GROUP_DICT_TYPE = SUBSTR(A.TMP, 1, LENGTH(A.TMP) - 2)) COOPERATION_PRODUCT_CATE_DESC,
       COOPERATION_SUBCATEGORY,
       (SELECT LISTAGG(B.COMPANY_DICT_NAME, ';')
          FROM (SELECT DISTINCT REGEXP_SUBSTR(A.TMP, '[^;]+', 1, LEVEL) COL
                  FROM (SELECT COOPERATION_SUBCATEGORY TMP
                          FROM SCMDATA.T_ASK_SCOPE
                         WHERE OBJECT_ID = :ASK_RECORD_ID) A
                CONNECT BY LEVEL <= REGEXP_COUNT(A.TMP, ';') + 1) Z
         INNER JOIN SCMDATA.SYS_COMPANY_DICT B
            ON Z.COL = B.COMPANY_DICT_VALUE
           AND B.COMPANY_DICT_TYPE = SUBSTR(Z.COL, 1, LENGTH(Z.COL) - 2)) COOPERATION_SUBCATEGORY_DESC
  FROM SCMDATA.T_ASK_SCOPE
 WHERE OBJECT_ID = :ASK_RECORD_ID^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_DEFAULT WHERE ELEMENT_ID = ''default_a_coop_159_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_DEFAULT SET (DEFAULT_SQL) = (SELECT :CV1 FROM DUAL) WHERE ELEMENT_ID = ''default_a_coop_159_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_DEFAULT (ELEMENT_ID,DEFAULT_SQL) SELECT :CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^SELECT TFA.COMPANY_NAME ASK_COMPANY_NAME,
       (SELECT PROVINCE
          FROM SCMDATA.DIC_PROVINCE
         WHERE PROVINCEID = A.COMPANY_PROVINCE) ||
       (SELECT CITY FROM SCMDATA.DIC_CITY WHERE CITYNO = A.COMPANY_CITY) ||
       (SELECT COUNTY
          FROM SCMDATA.DIC_COUNTY
         WHERE COUNTYID = A.COMPANY_COUNTY) PCC,
       (SELECT PROVINCE
          FROM SCMDATA.DIC_PROVINCE
         WHERE PROVINCEID = TFA.FACTORY_PROVINCE) ||
       (SELECT CITY FROM SCMDATA.DIC_CITY WHERE CITYNO = TFA.FACTORY_CITY) ||
       (SELECT COUNTY
          FROM SCMDATA.DIC_COUNTY
         WHERE COUNTYID = TFA.FACTORY_COUNTY) FPCC,
       TFA.COMPANY_PROVINCE COMPANY_PROVINCE,
       TFA.COMPANY_CITY COMPANY_CITY,
       TFA.COMPANY_COUNTY COMPANY_COUNTY,
       (SELECT NICK_NAME FROM SCMDATA.SYS_USER WHERE USER_ID = A.CREATE_ID) CONTACT_NAME,
       (SELECT PHONE FROM SCMDATA.SYS_USER WHERE USER_ID = A.CREATE_ID) CONTACT_PHONE,
       A.COOPERATION_TYPE,
       A.COOPERATION_MODEL,
       A.COMPANY_ADDRESS,
       A.SOCIAL_CREDIT_CODE
  FROM SCMDATA.T_FACTORY_ASK TFA
  LEFT JOIN SCMDATA.T_ASK_RECORD A
       ON TFA.ASK_RECORD_ID = A.ASK_RECORD_ID
 WHERE TFA.FACTORY_ASK_ID=:FACTORY_ASK_ID^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_DEFAULT WHERE ELEMENT_ID = ''default_a_coop_150_3_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_DEFAULT SET (DEFAULT_SQL) = (SELECT :CV1 FROM DUAL) WHERE ELEMENT_ID = ''default_a_coop_150_3_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_DEFAULT (ELEMENT_ID,DEFAULT_SQL) SELECT :CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^SELECT (SELECT NICK_NAME FROM SCMDATA.SYS_USER WHERE USER_ID = %CURRENT_USERID%) CHECKAPPLY_PERSON,
       (SELECT PHONE FROM SCMDATA.SYS_USER WHERE USER_ID = %CURRENT_USERID%) CHECK_APPLY_PHONE,
       SYSDATE CHECK_DATE,
       (SELECT DEPT_NAME
          FROM SCMDATA.SYS_COMPANY_DEPT
         WHERE COMPANY_DEPT_ID =
               (SELECT COMPANY_DEPT_ID
                  FROM SCMDATA.SYS_COMPANY_USER_DEPT
                 WHERE COMPANY_ID = :COMPANY_ID
                   AND USER_ID = :USER_ID)) CHECK_DEPT_NAME
  FROM DUAL^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_DEFAULT WHERE ELEMENT_ID = ''default_a_coop_150_3_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_DEFAULT SET (DEFAULT_SQL) = (SELECT :CV1 FROM DUAL) WHERE ELEMENT_ID = ''default_a_coop_150_3_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_DEFAULT (ELEMENT_ID,DEFAULT_SQL) SELECT :CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^select '80%' product_efficiency from dual^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_DEFAULT WHERE ELEMENT_ID = ''default_a_supp_171''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_DEFAULT SET (DEFAULT_SQL) = (SELECT :CV1 FROM DUAL) WHERE ELEMENT_ID = ''default_a_supp_171''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_DEFAULT (ELEMENT_ID,DEFAULT_SQL) SELECT :CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^select '80%' product_efficiency from dual^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_DEFAULT WHERE ELEMENT_ID = ''default_a_supp_171''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_DEFAULT SET (DEFAULT_SQL) = (SELECT :CV1 FROM DUAL) WHERE ELEMENT_ID = ''default_a_supp_171''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_DEFAULT (ELEMENT_ID,DEFAULT_SQL) SELECT :CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

