CREATE OR REPLACE TRIGGER SCMDATA.T_ORDER_FACCODE_AFTER_UPDATE
AFTER UPDATE OF FACTORY_CODE ON SCMDATA.T_ORDERS
FOR EACH ROW
BEGIN
  IF UPDATING THEN
    UPDATE SCMDATA.T_PRODUCTION_PROGRESS
      SET FACTORY_CODE = :NEW.FACTORY_CODE
     WHERE COMPANY_ID = :OLD.COMPANY_ID
       AND ORDER_ID   = :OLD.ORDER_ID
       AND GOO_ID     = :OLD.GOO_ID;
  END IF;
END;
/

