CREATE OR REPLACE TRIGGER SCMDATA.TRG_SYS_FIELD_LIST_WMSITF_LIMIT
BEFORE INSERT OR UPDATE
ON BW3.SYS_FIELD_LIST
FOR EACH ROW
BEGIN
 IF INSTR(',SCAN_TIME,PCOME_DATE,RECEIVE_TIME,PICK_TIME_GOO,SHIPMENT_TIME_GOO,PICK_TIME_SKU,SHIPMENT_TIME_SKU,RECEIVE_TIME_SKU,', ','||:NEW.FIELD_NAME||',')>0 THEN
   RAISE_APPLICATION_ERROR(-20002,'WMS接口字段，不能将 SYS_FIELD_LIST.FIELD_NAME 新增/修改为 '||:NEW.FIELD_NAME);
 END IF;
END;
/

