DECLARE
v_sql CLOB;
BEGIN
  v_sql := '
{
DECLARE
  V_CATE VARCHAR2(128);
  V_SQL  CLOB;
BEGIN

  IF :FACTORY_ASK_ID IS NULL THEN
    V_SQL := ''SELECT SUPPLIER_INFO_ID      RELA_SUPPLIER_ID,
       SUPPLIER_COMPANY_NAME RELA_SUPPLIER_ID_DESC
  FROM SCMDATA.T_SUPPLIER_INFO
 WHERE COMPANY_ID =%DEFAULT_COMPANY_ID%
   AND STATUS = 1'';

  ELSIF :FACTORY_ASK_ID IS NOT NULL and :COOPERATION_MODEL = ''OF''THEN
  SELECT LISTAGG(COOPERATION_CLASSIFICATION, '';'') WITHIN GROUP(ORDER BY 1)
    INTO V_CATE
      FROM SCMDATA.T_ASK_SCOPE A
     WHERE A.OBJECT_ID IN (SELECT T.ASK_RECORD_ID
         FROM SCMDATA.T_FACTORY_ASK T
        WHERE T.FACTORY_ASK_ID = :FACTORY_ASK_ID)
       AND A.COMPANY_ID = %DEFAULT_COMPANY_ID%;

    V_SQL := q''[SELECT DISTINCT A.SUPPLIER_INFO_ID      RELA_SUPPLIER_ID,
       A.SUPPLIER_COMPANY_NAME RELA_SUPPLIER_ID_DESC
  FROM SCMDATA.T_SUPPLIER_INFO A
  INNER JOIN SCMDATA.T_COOP_SCOPE B ON A.SUPPLIER_INFO_ID=B.SUPPLIER_INFO_ID AND A.COMPANY_ID=B.COMPANY_ID
 WHERE A.COMPANY_ID = %default_company_id%
   AND A.pause <> 1
   AND A.STATUS = 1
   AND B.PAUSE = 0
   AND A.COOPERATION_MODEL <> ''OF''
   AND  SCMDATA.INSTR_PRIV('']''|| V_CATE ||
             q''['', B.COOP_CLASSIFICATION)>0 ]'';
  END IF;
  @STRRESULT :=V_SQL;
END;
}';
UPDATE bw3.sys_look_up t SET t.look_up_sql = v_sql WHERE t.element_id = 'lookup_a_coop_150_3_0'; 
END;
/
