BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_3'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_310]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_3'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_3'',''asso_a_coop_150_0'',0,q''[a_coop_310]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_4'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_check_101]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_4'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_4'',''asso_a_coop_150_0'',0,q''[a_check_101]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_checkaction_a_supp_151'' AND CTL_ID = ''action_a_supp_151_5''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 2,q''[]'',91,0,2 FROM DUAL) WHERE  COND_ID = ''cond_checkaction_a_supp_151'' AND CTL_ID = ''action_a_supp_151_5''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_checkaction_a_supp_151'',''action_a_supp_151_5'',2,q''[]'',91,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_150]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_1'',''asso_a_coop_150_0'',0,q''[a_coop_150]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_2'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_230]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_2'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_2'',''asso_a_coop_150_0'',0,q''[a_coop_230]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_3'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_310]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_3'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_3'',''asso_a_coop_150_0'',0,q''[a_coop_310]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_4'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_check_101]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_4'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_4'',''asso_a_coop_150_0'',0,q''[a_check_101]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_6'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_320]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_6'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_6'',''asso_a_coop_150_0'',0,q''[a_coop_320]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_5'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_check_102]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_5'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_5'',''asso_a_coop_150_0'',0,q''[a_check_102]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_210]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto'',''asso_a_coop_150_0'',0,q''[a_coop_210]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_node_a_coop_150_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_220]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_node_a_coop_150_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_node_a_coop_150_auto_1'',''asso_a_coop_150_0'',0,q''[a_coop_220]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_checkaction_a_supp_160_1_3'' AND CTL_ID = ''action_a_supp_160_1_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 2,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_checkaction_a_supp_160_1_3'' AND CTL_ID = ''action_a_supp_160_1_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_checkaction_a_supp_160_1_3'',''action_a_supp_160_1_3'',2,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_ac_a_coop_150_1_auto'' AND CTL_ID = ''ac_a_coop_150_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_ac_a_coop_150_1_auto'' AND CTL_ID = ''ac_a_coop_150_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_ac_a_coop_150_1_auto'',''ac_a_coop_150_1'',0,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_6'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_320]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_6'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_6'',''asso_a_coop_150_0'',0,q''[a_coop_320]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_5'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_check_102]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_5'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_5'',''asso_a_coop_150_0'',0,q''[a_check_102]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_3_auto'' AND CTL_ID = ''asso_a_coop_150_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_150]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_3_auto'' AND CTL_ID = ''asso_a_coop_150_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_3_auto'',''asso_a_coop_150_3'',0,q''[a_coop_150]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_6_auto'' AND CTL_ID = ''asso_a_coop_150_6''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_150]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_6_auto'' AND CTL_ID = ''asso_a_coop_150_6''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_6_auto'',''asso_a_coop_150_6'',0,q''[a_coop_150]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_coop_150'' AND CTL_ID = ''action_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 1,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_coop_150'' AND CTL_ID = ''action_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_coop_150'',''action_a_coop_150_0'',1,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_associate_a_supp_151_4_auto'' AND CTL_ID = ''associate_a_supp_151_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_161_1]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_associate_a_supp_151_4_auto'' AND CTL_ID = ''associate_a_supp_151_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_associate_a_supp_151_4_auto'',''associate_a_supp_151_4'',0,q''[a_supp_161_1]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_210]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto'',''asso_a_coop_150_0'',0,q''[a_coop_210]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_node_a_coop_150_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_220]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_node_a_coop_150_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_node_a_coop_150_auto_1'',''asso_a_coop_150_0'',0,q''[a_coop_220]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_a_coop_150_0_auto'' AND CTL_ID = ''action_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_action_a_coop_150_0_auto'' AND CTL_ID = ''action_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_a_coop_150_0_auto'',''action_a_coop_150_0'',0,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_150]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_1'',''asso_a_coop_150_0'',0,q''[a_coop_150]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_specialapply_auto'' AND CTL_ID = ''action_specialapply''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_action_specialapply_auto'' AND CTL_ID = ''action_specialapply''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_specialapply_auto'',''action_specialapply'',0,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_2'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_230]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_2'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_2'',''asso_a_coop_150_0'',0,q''[a_coop_230]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_150]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_1'',''asso_a_coop_150_0'',0,q''[a_coop_150]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_2'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_230]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_2'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_2'',''asso_a_coop_150_0'',0,q''[a_coop_230]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_associate_a_supp_150_2_auto'' AND CTL_ID = ''associate_a_supp_150_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_150]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_associate_a_supp_150_2_auto'' AND CTL_ID = ''associate_a_supp_150_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_associate_a_supp_150_2_auto'',''associate_a_supp_150_2'',0,q''[a_supp_150]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto_1'' AND CTL_ID = ''associate_a_supp_110_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_160]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto_1'' AND CTL_ID = ''associate_a_supp_110_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_associate_a_supp_110_3_auto_1'',''associate_a_supp_110_3'',0,q''[a_supp_160]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_3'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_310]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_3'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_3'',''asso_a_coop_150_0'',0,q''[a_coop_310]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_4'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_check_101]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_4'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_4'',''asso_a_coop_150_0'',0,q''[a_check_101]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_supp_150_1'' AND CTL_ID = ''action_a_supp_150_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 1,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_supp_150_1'' AND CTL_ID = ''action_a_supp_150_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_supp_150_1'',''action_a_supp_150_1'',1,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_6'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_320]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_6'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_6'',''asso_a_coop_150_0'',0,q''[a_coop_320]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_5'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_check_102]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto_5'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto_5'',''asso_a_coop_150_0'',0,q''[a_check_102]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_a_supp_150_1_auto'' AND CTL_ID = ''action_a_supp_150_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_action_a_supp_150_1_auto'' AND CTL_ID = ''action_a_supp_150_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_a_supp_150_1_auto'',''action_a_supp_150_1'',0,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_supp_100'' AND CTL_ID = ''node_a_supp_100''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',0,0, FROM DUAL) WHERE  COND_ID = ''cond_a_supp_100'' AND CTL_ID = ''node_a_supp_100''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_supp_100'',''node_a_supp_100'',0,q''[]'',0,0, FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_210]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_0_auto'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_0_auto'',''asso_a_coop_150_0'',0,q''[a_coop_210]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_node_a_coop_150_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_220]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_node_a_coop_150_auto_1'' AND CTL_ID = ''asso_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_node_a_coop_150_auto_1'',''asso_a_coop_150_0'',0,q''[a_coop_220]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_node_a_coop_150_auto'' AND CTL_ID = ''node_a_coop_150''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',0,0,1 FROM DUAL) WHERE  COND_ID = ''cond_node_a_coop_150_auto'' AND CTL_ID = ''node_a_coop_150''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_node_a_coop_150_auto'',''node_a_coop_150'',0,q''[]'',0,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_node_a_supp_100_auto'' AND CTL_ID = ''node_a_supp_100''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',0,0,1 FROM DUAL) WHERE  COND_ID = ''cond_node_a_supp_100_auto'' AND CTL_ID = ''node_a_supp_100''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_node_a_supp_100_auto'',''node_a_supp_100'',0,q''[]'',0,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_specialapply_auto'' AND CTL_ID = ''action_specialapply''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_action_specialapply_auto'' AND CTL_ID = ''action_specialapply''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_specialapply_auto'',''action_specialapply'',0,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_checkaction_a_supp_160'' AND CTL_ID = ''action_a_supp_160''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 2,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_checkaction_a_supp_160'' AND CTL_ID = ''action_a_supp_160''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_checkaction_a_supp_160'',''action_a_supp_160'',2,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_a_supp_160_auto'' AND CTL_ID = ''action_a_supp_160''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_action_a_supp_160_auto'' AND CTL_ID = ''action_a_supp_160''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_a_supp_160_auto'',''action_a_supp_160'',0,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_node_a_coop_312'' AND CTL_ID = ''node_a_check_102_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',0,0,1 FROM DUAL) WHERE  COND_ID = ''cond_node_a_coop_312'' AND CTL_ID = ''node_a_check_102_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_node_a_coop_312'',''node_a_check_102_1'',0,q''[]'',0,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto'' AND CTL_ID = ''associate_a_supp_110_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_150]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto'' AND CTL_ID = ''associate_a_supp_110_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_associate_a_supp_110_3_auto'',''associate_a_supp_110_3'',0,q''[a_supp_150]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto_1'' AND CTL_ID = ''associate_a_supp_110_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_160]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto_1'' AND CTL_ID = ''associate_a_supp_110_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_associate_a_supp_110_3_auto_1'',''associate_a_supp_110_3'',0,q''[a_supp_160]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_coop_150_3'' AND CTL_ID = ''a_coop_150_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 1,q''[]'',14,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_coop_150_3'' AND CTL_ID = ''a_coop_150_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_coop_150_3'',''a_coop_150_3'',1,q''[]'',14,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_checkaction_a_supp_151'' AND CTL_ID = ''action_a_supp_151_5''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 2,q''[]'',91,0,2 FROM DUAL) WHERE  COND_ID = ''cond_checkaction_a_supp_151'' AND CTL_ID = ''action_a_supp_151_5''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_checkaction_a_supp_151'',''action_a_supp_151_5'',2,q''[]'',91,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_node_a_check_102_auto'' AND CTL_ID = ''node_a_check_102''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',0,0,1 FROM DUAL) WHERE  COND_ID = ''cond_node_a_check_102_auto'' AND CTL_ID = ''node_a_check_102''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_node_a_check_102_auto'',''node_a_check_102'',0,q''[]'',0,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_node_a_check_103_auto'' AND CTL_ID = ''node_a_check_103''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',0,0,1 FROM DUAL) WHERE  COND_ID = ''cond_node_a_check_103_auto'' AND CTL_ID = ''node_a_check_103''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_node_a_check_103_auto'',''node_a_check_103'',0,q''[]'',0,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_a_supp_160_1_auto'' AND CTL_ID = ''action_a_supp_160_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_action_a_supp_160_1_auto'' AND CTL_ID = ''action_a_supp_160_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_a_supp_160_1_auto'',''action_a_supp_160_1'',0,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_associate_a_supp_151_4_auto'' AND CTL_ID = ''associate_a_supp_151_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_161_1]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_associate_a_supp_151_4_auto'' AND CTL_ID = ''associate_a_supp_151_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_associate_a_supp_151_4_auto'',''associate_a_supp_151_4'',0,q''[a_supp_161_1]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_coop_150_6_auto'' AND CTL_ID = ''a_coop_150_6''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',14,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_coop_150_6_auto'' AND CTL_ID = ''a_coop_150_6''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_coop_150_6_auto'',''a_coop_150_6'',0,q''[]'',14,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_coop_150_6_auto_1'' AND CTL_ID = ''a_coop_150_6''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',13,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_coop_150_6_auto_1'' AND CTL_ID = ''a_coop_150_6''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_coop_150_6_auto_1'',''a_coop_150_6'',0,q''[]'',13,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_asso_a_coop_150_3_auto'' AND CTL_ID = ''asso_a_coop_150_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_coop_150]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_asso_a_coop_150_3_auto'' AND CTL_ID = ''asso_a_coop_150_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_asso_a_coop_150_3_auto'',''asso_a_coop_150_3'',0,q''[a_coop_150]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_coop_150_auto'' AND CTL_ID = ''a_coop_150''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',14,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_coop_150_auto'' AND CTL_ID = ''a_coop_150''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_coop_150_auto'',''a_coop_150'',0,q''[]'',14,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_check_103_auto'' AND CTL_ID = ''a_check_103''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',14,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_check_103_auto'' AND CTL_ID = ''a_check_103''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_check_103_auto'',''a_check_103'',0,q''[]'',14,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_checkaction_a_supp_160_1_3'' AND CTL_ID = ''action_a_supp_160_1_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 2,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_checkaction_a_supp_160_1_3'' AND CTL_ID = ''action_a_supp_160_1_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_checkaction_a_supp_160_1_3'',''action_a_supp_160_1_3'',2,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_a_supp_160_2_auto'' AND CTL_ID = ''action_a_supp_160_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_action_a_supp_160_2_auto'' AND CTL_ID = ''action_a_supp_160_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_a_supp_160_2_auto'',''action_a_supp_160_2'',0,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_g_501_4'' AND CTL_ID = ''action_g_501_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0, FROM DUAL) WHERE  COND_ID = ''cond_action_g_501_4'' AND CTL_ID = ''action_g_501_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_g_501_4'',''action_g_501_4'',0,q''[]'',91,0, FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_supp_150_auto'' AND CTL_ID = ''a_supp_150''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',14,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_supp_150_auto'' AND CTL_ID = ''a_supp_150''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_supp_150_auto'',''a_supp_150'',0,q''[]'',14,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_g_501_3'' AND CTL_ID = ''action_g_501_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0, FROM DUAL) WHERE  COND_ID = ''cond_action_g_501_3'' AND CTL_ID = ''action_g_501_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_g_501_3'',''action_g_501_3'',0,q''[]'',91,0, FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_g_501_2'' AND CTL_ID = ''action_g_501_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0, FROM DUAL) WHERE  COND_ID = ''cond_action_g_501_2'' AND CTL_ID = ''action_g_501_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_g_501_2'',''action_g_501_2'',0,q''[]'',91,0, FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto'' AND CTL_ID = ''associate_a_supp_110_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_150]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto'' AND CTL_ID = ''associate_a_supp_110_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_associate_a_supp_110_3_auto'',''associate_a_supp_110_3'',0,q''[a_supp_150]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto_1'' AND CTL_ID = ''associate_a_supp_110_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_160]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto_1'' AND CTL_ID = ''associate_a_supp_110_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_associate_a_supp_110_3_auto_1'',''associate_a_supp_110_3'',0,q''[a_supp_160]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_checkaction_a_supp_111_2'' AND CTL_ID = ''action_a_supp_111_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 1,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_checkaction_a_supp_111_2'' AND CTL_ID = ''action_a_supp_111_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_checkaction_a_supp_111_2'',''action_a_supp_111_2'',1,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_a_supp_161_1_1_auto'' AND CTL_ID = ''action_a_supp_161_1_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_161_1]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_action_a_supp_161_1_1_auto'' AND CTL_ID = ''action_a_supp_161_1_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_a_supp_161_1_1_auto'',''action_a_supp_161_1_1'',0,q''[a_supp_161_1]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_a_supp_161_1_2_auto'' AND CTL_ID = ''action_a_supp_161_1_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_161_1]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_action_a_supp_161_1_2_auto'' AND CTL_ID = ''action_a_supp_161_1_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_a_supp_161_1_2_auto'',''action_a_supp_161_1_2'',0,q''[a_supp_161_1]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_action_a_supp_160_6_auto'' AND CTL_ID = ''action_a_supp_160_6''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_action_a_supp_160_6_auto'' AND CTL_ID = ''action_a_supp_160_6''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_action_a_supp_160_6_auto'',''action_a_supp_160_6'',0,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_supp_160_6'' AND CTL_ID = ''action_a_supp_160_6''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 1,q''[]'',91,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_supp_160_6'' AND CTL_ID = ''action_a_supp_160_6''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_supp_160_6'',''action_a_supp_160_6'',1,q''[]'',91,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_supp_160_auto'' AND CTL_ID = ''a_supp_160''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',14,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_supp_160_auto'' AND CTL_ID = ''a_supp_160''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_supp_160_auto'',''a_supp_160'',0,q''[]'',14,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_supp_161_auto'' AND CTL_ID = ''a_supp_161''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',13,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_supp_161_auto'' AND CTL_ID = ''a_supp_161''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_supp_161_auto'',''a_supp_161'',0,q''[]'',13,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_supp_161_1_auto'' AND CTL_ID = ''a_supp_161_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',14,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_supp_161_1_auto'' AND CTL_ID = ''a_supp_161_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_supp_161_1_auto'',''a_supp_161_1'',0,q''[]'',14,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_supp_161_1_auto_1'' AND CTL_ID = ''a_supp_161_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',11,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_supp_161_1_auto_1'' AND CTL_ID = ''a_supp_161_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_supp_161_1_auto_1'',''a_supp_161_1'',0,q''[]'',11,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto'' AND CTL_ID = ''associate_a_supp_110_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[a_supp_150]'',95,0,1 FROM DUAL) WHERE  COND_ID = ''cond_associate_a_supp_110_3_auto'' AND CTL_ID = ''associate_a_supp_110_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_associate_a_supp_110_3_auto'',''associate_a_supp_110_3'',0,q''[a_supp_150]'',95,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_supp_161_1_auto_2'' AND CTL_ID = ''a_supp_161_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',13,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_supp_161_1_auto_2'' AND CTL_ID = ''a_supp_161_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_supp_161_1_auto_2'',''a_supp_161_1'',0,q''[]'',13,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_a_supp_161_1_auto_3'' AND CTL_ID = ''a_supp_161_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',12,0,1 FROM DUAL) WHERE  COND_ID = ''cond_a_supp_161_1_auto_3'' AND CTL_ID = ''a_supp_161_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_a_supp_161_1_auto_3'',''a_supp_161_1'',0,q''[]'',12,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

