BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ASSOCIATE WHERE ELEMENT_ID = ''associate_c_2420_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ASSOCIATE SET (ASSOCIATE_TYPE,CAPTION,DATA_TYPE,FIELD_NAME,ICON_NAME,NODE_ID,OPEN_TYPE,DATA_SQL) = (SELECT 6,q''[×Ö¶ÎÅäÖÃ£¨ASS£©]'',2,q''[DATA_PRIV_ID]'',q''[]'',q''[node_c_2431]'',q''[]'',:CV1 FROM DUAL) WHERE ELEMENT_ID = ''associate_c_2420_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ASSOCIATE (ASSOCIATE_TYPE,CAPTION,DATA_TYPE,ELEMENT_ID,FIELD_NAME,ICON_NAME,NODE_ID,OPEN_TYPE,DATA_SQL) SELECT 6,q''[×Ö¶ÎÅäÖÃ£¨ASS£©]'',2,''associate_c_2420_1'',q''[DATA_PRIV_ID]'',q''[]'',q''[node_c_2431]'',q''[]'',:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

