DECLARE 
  V_SELSQL  CLOB:=q'^{DECLARE
  V_ISADMIN   VARCHAR2(10):=%IS_COMPANY_ADMIN%;
  V_COMPID    VARCHAR2(32):=%DEFAULT_COMPANY_ID%;
  V_DATAPRIV  VARCHAR2(32):=SCMDATA.PKG_DATA_PRIVS.PARSE_JSON(P_JSONSTR => %DATA_PRIVS_JSON_STRS%,P_KEY => 'COL_2');
  V_EXESQL    CLOB;
BEGIN
  V_EXESQL := 'WITH GDIC AS
 (SELECT GROUP_DICT_NAME, GROUP_DICT_VALUE, GROUP_DICT_TYPE
    FROM SCMDATA.SYS_GROUP_DICT)
SELECT Z.ORDER_CODE,
       Z.ORDER_STATUS,
       (SELECT GROUP_DICT_NAME
          FROM SCMDATA.SYS_GROUP_DICT
         WHERE GROUP_DICT_VALUE = Z.ORDER_STATUS
           AND GROUP_DICT_TYPE = ''ORDER_STATUS'') ORDER_STATUS_DESC,
       (SELECT SUPPLIER_COMPANY_NAME
          FROM SCMDATA.T_SUPPLIER_INFO
         WHERE SUPPLIER_CODE = Z.SUPPLIER_CODE
           AND COMPANY_ID = Z.COMPANY_ID) SUPPLIER,
       X.RELA_GOO_ID,
       X.STYLE_NUMBER,
       Y.FACTORY_CODE,
       SUP1.SUPPLIER_COMPANY_NAME PRODUCT_FACTORY,
       (SELECT LISTAGG(COMPANY_USER_NAME, '','')
          FROM SCMDATA.SYS_COMPANY_USER
         WHERE INSTR('','' || Z.DEAL_FOLLOWER || '','', '','' || USER_ID || '','') > 0
           AND COMPANY_ID = Z.COMPANY_ID) DEAL_FOLLOWER,
       Z.DELIVERY_DATE,
       MAX(Y.DELIVERY_DATE) OVER(PARTITION BY Y.ORDER_ID, Y.COMPANY_ID) LATEST_DELIVERY_DATE,
       Y.ORDER_AMOUNT,
       Y.ORDER_PRICE SINGLE_PRICE,
       Y.ORDER_PRICE * Y.ORDER_AMOUNT ORDER_SUM,
       Z.MEMO,
       (SELECT GROUP_DICT_NAME
          FROM GDIC
         WHERE GROUP_DICT_VALUE = Z.ORDER_TYPE
           AND GROUP_DICT_TYPE = ''ORDER_TYPE'') ORDER_TYPE,
       X.STYLE_NAME,
       X.GOO_NAME,
       SUP1.LOCATION,
       SUP1.GROUP_NAME,
       SUP1.AREA_GROUP_LEADER,
       (SELECT GROUP_DICT_NAME
          FROM GDIC
         WHERE GROUP_DICT_VALUE = X.CATEGORY
           AND GROUP_DICT_TYPE = ''PRODUCT_TYPE'') CATEGORY,
       (SELECT GROUP_DICT_NAME
          FROM GDIC
         WHERE GROUP_DICT_VALUE = X.PRODUCT_CATE
           AND GROUP_DICT_TYPE = X.CATEGORY) PRODUCT_CATE,
       (SELECT COMPANY_DICT_NAME
          FROM SCMDATA.SYS_COMPANY_DICT
         WHERE COMPANY_DICT_VALUE = X.SAMLL_CATEGORY
           AND COMPANY_DICT_TYPE = X.PRODUCT_CATE
           AND COMPANY_ID = Z.COMPANY_ID) SAMLL_CATEGORY_GD,
       (SELECT LISTAGG(COMPANY_USER_NAME, '','')
          FROM SCMDATA.SYS_COMPANY_USER
         WHERE INNER_USER_ID = Z.SEND_ORDER
           AND COMPANY_ID = Z.COMPANY_ID) SEND_ORDER,
       CASE
         WHEN Z.SEND_BY_SUP = 0 THEN
          ''否''
         WHEN Z.SEND_BY_SUP = 1 THEN
          ''是''
       END SEND_BY_SUP,
       Z.RATIONAME RATIONAME_00000,
       Z.SEND_ORDER_DATE SEND_ORDER_DATE,
       TO_CHAR(Z.FINISH_TIME_SCM, ''yyyy-MM-dd'') FINISH_TIME_SCM,
       X.GOO_ID,
       (SELECT COMPANY_USER_NAME
          FROM SCMDATA.SYS_COMPANY_USER
         WHERE COMPANY_ID = Z.COMPANY_ID
           AND USER_ID = Z.UPDATE_ID) UPDATE_ID,
       Z.UPDATE_TIME,
       Z.ORDER_ID
  FROM (SELECT ORDER_ID,
                ORDER_CODE,
                ORDER_STATUS,
                SUPPLIER_CODE,
                MEMO,
                ORDER_TYPE,
                SEND_ORDER,
                SEND_ORDER_DATE,
                FINISH_TIME_SCM,
                COMPANY_ID,
                UPDATE_ID,
                UPDATE_TIME,
                DELIVERY_DATE,
                DEAL_FOLLOWER,
                SEND_BY_SUP,
                RATIONAME
           FROM SCMDATA.T_ORDERED
          WHERE COMPANY_ID = '''||V_COMPID||'''
            AND ORDER_STATUS IN (''OS01'', ''OS00'')
       AND IS_PRODUCT_ORDER = 1) Z
 INNER JOIN SCMDATA.T_ORDERS Y
    ON Z.ORDER_CODE = Y.ORDER_ID
   AND Z.COMPANY_ID = Y.COMPANY_ID
  LEFT JOIN (SELECT TMPSUP.SUPPLIER_CODE,
                    TMPSUP.COMPANY_ID,
                    TMPSUP.SUPPLIER_COMPANY_NAME,
                    DIC1.PROVINCE || DIC2.CITY || DIC3.COUNTY LOCATION,
                    SUPGROUPCFG.GROUP_NAME,
                    CU.COMPANY_USER_NAME AREA_GROUP_LEADER
               FROM SCMDATA.T_SUPPLIER_INFO TMPSUP
               LEFT JOIN SCMDATA.DIC_PROVINCE DIC1
                 ON TMPSUP.COMPANY_PROVINCE = DIC1.PROVINCEID
                AND DIC1.PAUSE = 0
               LEFT JOIN SCMDATA.DIC_CITY DIC2
                 ON TMPSUP.COMPANY_CITY = DIC2.CITYNO
                AND TMPSUP.COMPANY_PROVINCE = DIC2.PROVINCEID
                AND DIC2.PAUSE = 0
               LEFT JOIN SCMDATA.DIC_COUNTY DIC3
                 ON TMPSUP.COMPANY_COUNTY = DIC3.COUNTYID
                AND TMPSUP.COMPANY_CITY = DIC3.CITYNO
                AND DIC3.PAUSE = 0
               LEFT JOIN SCMDATA.T_SUPPLIER_GROUP_CONFIG SUPGROUPCFG
                 ON TMPSUP.GROUP_NAME = SUPGROUPCFG.GROUP_CONFIG_ID
                AND TMPSUP.COMPANY_ID = SUPGROUPCFG.COMPANY_ID
                AND SUPGROUPCFG.PAUSE = 1
               LEFT JOIN SCMDATA.SYS_COMPANY_USER CU
                 ON SUPGROUPCFG.AREA_GROUP_LEADER = CU.USER_ID
                AND SUPGROUPCFG.COMPANY_ID = CU.COMPANY_ID
              WHERE TMPSUP.INSIDE_SUPPLIER_CODE NOT IN (''30928'',''73036'')) SUP1
    ON Y.FACTORY_CODE = SUP1.SUPPLIER_CODE
   AND Y.COMPANY_ID = SUP1.COMPANY_ID
 INNER JOIN SCMDATA.T_COMMODITY_INFO X
    ON X.GOO_ID = Y.GOO_ID
   AND X.COMPANY_ID = Y.COMPANY_ID
   AND (('||V_ISADMIN||' = 1)
       OR scmdata.instr_priv(p_str1  => '''||V_DATAPRIV||''',
                             p_str2  => X.CATEGORY,
                             p_split => '';'') > 0)';
  @StrResult := V_EXESQL;
END;}^';
BEGIN
  UPDATE BW3.SYS_ITEM_LIST 
     SET SELECT_SQL = V_SELSQL
   WHERE ITEM_ID = 'a_order_101_0';
END;
/

DECLARE 
  V_SELSQL  CLOB:=q'^{DECLARE
  V_ISADMIN   VARCHAR2(10):=%IS_COMPANY_ADMIN%;
  V_COMPID    VARCHAR2(32):=%DEFAULT_COMPANY_ID%;
  V_DATAPRIV  VARCHAR2(32):=SCMDATA.PKG_DATA_PRIVS.PARSE_JSON(P_JSONSTR => %DATA_PRIVS_JSON_STRS%,P_KEY => 'COL_2');
  V_EXESQL    CLOB;
BEGIN
  V_EXESQL := 'WITH GDIC AS
 (SELECT GROUP_DICT_NAME, GROUP_DICT_VALUE, GROUP_DICT_TYPE
    FROM SCMDATA.SYS_GROUP_DICT)
SELECT Z.ORDER_CODE,
       Z.ORDER_STATUS,
       (SELECT GROUP_DICT_NAME
          FROM SCMDATA.SYS_GROUP_DICT
         WHERE GROUP_DICT_VALUE = Z.ORDER_STATUS
           AND GROUP_DICT_TYPE = ''ORDER_STATUS'') ORDER_STATUS_DESC,
       (SELECT SUPPLIER_COMPANY_NAME
          FROM SCMDATA.T_SUPPLIER_INFO
         WHERE SUPPLIER_CODE = Z.SUPPLIER_CODE
           AND COMPANY_ID = Z.COMPANY_ID) SUPPLIER,
       X.RELA_GOO_ID,
       X.STYLE_NUMBER,
       Y.FACTORY_CODE,
       (SELECT SUPPLIER_COMPANY_NAME
          FROM SCMDATA.T_SUPPLIER_INFO
         WHERE COMPANY_ID = Z.COMPANY_ID
           AND SUPPLIER_CODE = Y.FACTORY_CODE) PRODUCT_FACTORY,
       (SELECT LISTAGG(COMPANY_USER_NAME,'','')
          FROM SCMDATA.SYS_COMPANY_USER
         WHERE INSTR('',''||Z.DEAL_FOLLOWER||'','', '',''||USER_ID||'','')>0
           AND COMPANY_ID = Z.COMPANY_ID) DEAL_FOLLOWER,
       Z.DELIVERY_DATE,
       MAX(Y.DELIVERY_DATE) OVER(PARTITION BY Y.ORDER_ID, Y.COMPANY_ID) LATEST_DELIVERY_DATE,
       Y.ORDER_AMOUNT,
       Y.ORDER_PRICE SINGLE_PRICE,
       Y.ORDER_PRICE * Y.ORDER_AMOUNT ORDER_SUM,
       Z.MEMO,
       (SELECT GROUP_DICT_NAME
          FROM GDIC
         WHERE GROUP_DICT_VALUE = Z.ORDER_TYPE
           AND GROUP_DICT_TYPE = ''ORDER_TYPE'') ORDER_TYPE,
       X.STYLE_NAME,
       X.GOO_NAME,
       Z.AREA_LOCATIOIN LOCATION,
       SUPGROUPCFG.GROUP_NAME,
       CU.COMPANY_USER_NAME AREA_GROUP_LEADER,
       (SELECT GROUP_DICT_NAME
          FROM GDIC
         WHERE GROUP_DICT_VALUE = X.CATEGORY
           AND GROUP_DICT_TYPE = ''PRODUCT_TYPE'') CATEGORY,
       (SELECT GROUP_DICT_NAME
          FROM GDIC
         WHERE GROUP_DICT_VALUE = X.PRODUCT_CATE
           AND GROUP_DICT_TYPE = X.CATEGORY) PRODUCT_CATE,
       (SELECT COMPANY_DICT_NAME
          FROM SCMDATA.SYS_COMPANY_DICT
         WHERE COMPANY_DICT_VALUE = X.SAMLL_CATEGORY
           AND COMPANY_DICT_TYPE = X.PRODUCT_CATE
           AND COMPANY_ID = Z.COMPANY_ID) SAMLL_CATEGORY_GD,
       (SELECT LISTAGG(COMPANY_USER_NAME,'','')
          FROM SCMDATA.SYS_COMPANY_USER
         WHERE INNER_USER_ID = Z.SEND_ORDER
           AND COMPANY_ID = Z.COMPANY_ID) SEND_ORDER,
       CASE WHEN Z.SEND_BY_SUP = 0 THEN ''否''
            WHEN Z.SEND_BY_SUP = 1 THEN ''是''
       END SEND_BY_SUP,
       (CASE WHEN Z.IS_PRODUCT_ORDER = 1 THEN ''是''
            WHEN Z.IS_PRODUCT_ORDER = 0 THEN ''否'' END) IS_PRODUCT_ORDER,
       Z.RATIONAME RATIONAME_00000,
       Z.SEND_ORDER_DATE SEND_ORDER_DATE,
       TO_CHAR(Z.FINISH_TIME_SCM, ''yyyy-MM-dd'') FINISH_TIME_SCM,
       X.GOO_ID,
       (SELECT COMPANY_USER_NAME
          FROM SCMDATA.SYS_COMPANY_USER
         WHERE COMPANY_ID = Z.COMPANY_ID
           AND USER_ID = Z.UPDATE_ID) UPDATE_ID,
       Z.UPDATE_TIME,
       Z.ORDER_ID
  FROM (SELECT ORDER_ID,ORDER_CODE,ORDER_STATUS,SUPPLIER_CODE,MEMO,
               ORDER_TYPE,SEND_ORDER,SEND_ORDER_DATE,FINISH_TIME_SCM,
               COMPANY_ID,UPDATE_ID,UPDATE_TIME,DELIVERY_DATE,DEAL_FOLLOWER,
               IS_PRODUCT_ORDER,SEND_BY_SUP,RATIONAME,AREA_GROUP_ID,
               AREA_GROUP_LEADERID,AREA_LOCATIOIN
          FROM SCMDATA.T_ORDERED
         WHERE ORDER_STATUS IN (''OS02'',''OS03'')
           AND COMPANY_ID = '''||V_COMPID||''') Z
 INNER JOIN SCMDATA.T_ORDERS Y
    ON Z.ORDER_CODE = Y.ORDER_ID
   AND Z.COMPANY_ID = Y.COMPANY_ID
  LEFT JOIN SCMDATA.T_SUPPLIER_GROUP_CONFIG SUPGROUPCFG
    ON Z.AREA_GROUP_ID = SUPGROUPCFG.GROUP_CONFIG_ID
   AND Z.COMPANY_ID = SUPGROUPCFG.COMPANY_ID
  LEFT JOIN SCMDATA.SYS_COMPANY_USER CU
    ON Z.AREA_GROUP_LEADERID = CU.USER_ID
   AND Z.COMPANY_ID = CU.COMPANY_ID
 INNER JOIN SCMDATA.T_COMMODITY_INFO X
    ON X.GOO_ID = Y.GOO_ID
   AND X.COMPANY_ID = Y.COMPANY_ID
   AND (('||V_ISADMIN||' = 1)
       OR scmdata.instr_priv(p_str1  => '''||V_DATAPRIV||''',
                             p_str2  => X.CATEGORY,
                             p_split => '';'') >0)';
  @StrResult := V_EXESQL;
END;}^';
BEGIN
  UPDATE BW3.SYS_ITEM_LIST 
     SET SELECT_SQL = V_SELSQL
   WHERE ITEM_ID = 'a_order_101_1';
END;
/

DECLARE 
  V_SELSQL  CLOB:=q'^{DECLARE
  V_ISADMIN   VARCHAR2(10):=%IS_COMPANY_ADMIN%;
  V_COMPID    VARCHAR2(32):=%DEFAULT_COMPANY_ID%;
  V_DATAPRIV  VARCHAR2(32):=SCMDATA.PKG_DATA_PRIVS.PARSE_JSON(P_JSONSTR => %DATA_PRIVS_JSON_STRS%,P_KEY => 'COL_2');
  V_EXESQL    CLOB;
BEGIN
  V_EXESQL := 'WITH GDIC AS
 (SELECT GROUP_DICT_NAME, GROUP_DICT_VALUE, GROUP_DICT_TYPE
    FROM SCMDATA.SYS_GROUP_DICT)
SELECT Z.ORDER_CODE,
       Z.ORDER_STATUS,
       (SELECT GROUP_DICT_NAME
          FROM SCMDATA.SYS_GROUP_DICT
         WHERE GROUP_DICT_VALUE = Z.ORDER_STATUS
           AND GROUP_DICT_TYPE = ''ORDER_STATUS'') ORDER_STATUS_DESC,
       (SELECT SUPPLIER_COMPANY_NAME
          FROM SCMDATA.T_SUPPLIER_INFO
         WHERE SUPPLIER_CODE = Z.SUPPLIER_CODE
           AND COMPANY_ID = Z.COMPANY_ID) SUPPLIER,
       X.RELA_GOO_ID,
       X.STYLE_NUMBER,
       Y.FACTORY_CODE,
       (SELECT SUPPLIER_COMPANY_NAME
          FROM SCMDATA.T_SUPPLIER_INFO
         WHERE COMPANY_ID = Z.COMPANY_ID
           AND SUPPLIER_CODE = Y.FACTORY_CODE) PRODUCT_FACTORY,
       (SELECT LISTAGG(COMPANY_USER_NAME,'','')
          FROM SCMDATA.SYS_COMPANY_USER
         WHERE INSTR('',''||Z.DEAL_FOLLOWER||'','', '',''||USER_ID||'','')>0
           AND COMPANY_ID = Z.COMPANY_ID) DEAL_FOLLOWER,
       Z.DELIVERY_DATE,
       MAX(Y.DELIVERY_DATE) OVER(PARTITION BY Y.ORDER_ID, Y.COMPANY_ID) LATEST_DELIVERY_DATE,
       Y.ORDER_AMOUNT,
       Y.ORDER_PRICE SINGLE_PRICE,
       Y.ORDER_PRICE * Y.ORDER_AMOUNT ORDER_SUM,
       Z.MEMO,
       (SELECT GROUP_DICT_NAME
          FROM GDIC
         WHERE GROUP_DICT_VALUE = Z.ORDER_TYPE
           AND GROUP_DICT_TYPE = ''ORDER_TYPE'') ORDER_TYPE,
       X.STYLE_NAME,
       X.GOO_NAME,
       SUP1.LOCATION,
       SUP1.GROUP_NAME,
       SUP1.AREA_GROUP_LEADER,
       (SELECT GROUP_DICT_NAME
          FROM GDIC
         WHERE GROUP_DICT_VALUE = X.CATEGORY
           AND GROUP_DICT_TYPE = ''PRODUCT_TYPE'') CATEGORY,
       (SELECT GROUP_DICT_NAME
          FROM GDIC
         WHERE GROUP_DICT_VALUE = X.PRODUCT_CATE
           AND GROUP_DICT_TYPE = X.CATEGORY) PRODUCT_CATE,
       (SELECT COMPANY_DICT_NAME
          FROM SCMDATA.SYS_COMPANY_DICT
         WHERE COMPANY_DICT_VALUE = X.SAMLL_CATEGORY
           AND COMPANY_DICT_TYPE = X.PRODUCT_CATE
           AND COMPANY_ID = Z.COMPANY_ID) SAMLL_CATEGORY_GD,
       (SELECT LISTAGG(COMPANY_USER_NAME,'','')
          FROM SCMDATA.SYS_COMPANY_USER
         WHERE INNER_USER_ID = Z.SEND_ORDER
           AND COMPANY_ID = Z.COMPANY_ID) SEND_ORDER,
       CASE WHEN Z.SEND_BY_SUP = 0 THEN ''否''
            WHEN Z.SEND_BY_SUP = 1 THEN ''是''
       END SEND_BY_SUP,
       Z.RATIONAME RATIONAME_00000,
       Z.SEND_ORDER_DATE SEND_ORDER_DATE,
       TO_CHAR(Z.FINISH_TIME_SCM, ''yyyy-MM-dd'') FINISH_TIME_SCM,
       X.GOO_ID,
       (SELECT COMPANY_USER_NAME
          FROM SCMDATA.SYS_COMPANY_USER
         WHERE COMPANY_ID = Z.COMPANY_ID
           AND USER_ID = Z.UPDATE_ID) UPDATE_ID,
       Z.UPDATE_TIME,
       Z.ORDER_ID
  FROM (SELECT ORDER_ID,ORDER_CODE,ORDER_STATUS,SUPPLIER_CODE,
               MEMO,ORDER_TYPE,SEND_ORDER,SEND_ORDER_DATE,
               FINISH_TIME_SCM,COMPANY_ID,UPDATE_ID,
               UPDATE_TIME,DELIVERY_DATE,DEAL_FOLLOWER,
               SEND_BY_SUP,RATIONAME,AREA_GROUP_ID,
               AREA_LOCATIOIN
          FROM SCMDATA.T_ORDERED
         WHERE COMPANY_ID = '''||V_COMPID||'''
           AND ORDER_STATUS IN (''OS01'', ''OS00'')
           AND IS_PRODUCT_ORDER = 0) Z
 INNER JOIN SCMDATA.T_ORDERS Y
    ON Z.ORDER_CODE = Y.ORDER_ID
   AND Z.COMPANY_ID = Y.COMPANY_ID
  LEFT JOIN (SELECT TMPSUP.SUPPLIER_CODE,
                    TMPSUP.COMPANY_ID,
                    TMPSUP.SUPPLIER_COMPANY_NAME,
                    DIC1.PROVINCE || DIC2.CITY || DIC3.COUNTY LOCATION,
                    SUPGROUPCFG.GROUP_NAME,
                    CU.COMPANY_USER_NAME AREA_GROUP_LEADER
               FROM SCMDATA.T_SUPPLIER_INFO TMPSUP
               LEFT JOIN SCMDATA.DIC_PROVINCE DIC1
                 ON TMPSUP.COMPANY_PROVINCE = DIC1.PROVINCEID
                AND DIC1.PAUSE = 0
               LEFT JOIN SCMDATA.DIC_CITY DIC2
                 ON TMPSUP.COMPANY_CITY = DIC2.CITYNO
                AND TMPSUP.COMPANY_PROVINCE = DIC2.PROVINCEID
                AND DIC2.PAUSE = 0
               LEFT JOIN SCMDATA.DIC_COUNTY DIC3
                 ON TMPSUP.COMPANY_COUNTY = DIC3.COUNTYID
                AND TMPSUP.COMPANY_CITY = DIC3.CITYNO
                AND DIC3.PAUSE = 0
               LEFT JOIN SCMDATA.T_SUPPLIER_GROUP_CONFIG SUPGROUPCFG
                 ON TMPSUP.GROUP_NAME = SUPGROUPCFG.GROUP_CONFIG_ID
                AND TMPSUP.COMPANY_ID = SUPGROUPCFG.COMPANY_ID
                AND SUPGROUPCFG.PAUSE = 1
               LEFT JOIN SCMDATA.SYS_COMPANY_USER CU
                 ON SUPGROUPCFG.AREA_GROUP_LEADER = CU.USER_ID
                AND SUPGROUPCFG.COMPANY_ID = CU.COMPANY_ID
              WHERE TMPSUP.INSIDE_SUPPLIER_CODE NOT IN (''30928'',''73036'')) SUP1
    ON Y.FACTORY_CODE = SUP1.SUPPLIER_CODE
   AND Y.COMPANY_ID = SUP1.COMPANY_ID
 INNER JOIN SCMDATA.T_COMMODITY_INFO X
    ON X.GOO_ID = Y.GOO_ID
   AND X.COMPANY_ID = Y.COMPANY_ID
   AND (('||V_ISADMIN||' = 1)
       OR scmdata.instr_priv(p_str1  => '''||V_DATAPRIV||''',
                             p_str2  => X.CATEGORY,
                             p_split => '';'') > 0)';
  @StrResult := V_EXESQL;
END;}^';
BEGIN
  UPDATE BW3.SYS_ITEM_LIST 
     SET SELECT_SQL = V_SELSQL
   WHERE ITEM_ID = 'a_order_101_3';
END;
/

DECLARE 
  V_SELSQL  CLOB:=q'^WITH DIC AS
  (SELECT GROUP_DICT_NAME,GROUP_DICT_VALUE,GROUP_DICT_TYPE
    FROM SCMDATA.SYS_GROUP_DICT)
SELECT DIC1.GROUP_DICT_NAME ANOMALY_CLASS,
       T.ORDER_ID PRODUCT_GRESS_CODE,
       DIC1.GROUP_DICT_NAME STATUS_DESC,
       T.DETAILED_REASONS,--问题描述
       T.DELAY_DATE,--延期天数
       T.DELAY_AMOUNT,--数量
       DIC2.GROUP_DICT_NAME HANDLE_OPINIONS,--处理结果
       CASE WHEN T.IS_DEDUCTION = 1 THEN '是' ELSE '否' END IS_DEDUCTION,--是否扣款
       DIC3.GROUP_DICT_NAME DEDUCTION_METHOD_DESC,--扣款方式
       T.DEDUCTION_UNIT_PRICE,--扣款单价/金额/比例
       T.FILE_ID,--附件
       T.PROBLEM_CLASS,--问题分类
       T.CAUSE_CLASS,--原因分类
       T.CAUSE_DETAILED CAUSE_DETAIL,--原因细分
       CASE WHEN T.IS_SUP_RESPONSIBLE = 1 THEN '是' ELSE '否' END IS_SUP_RESPONSIBLE,--供应商是否免责
       DEPT.DEPT_NAME,--责任部门（一级）
       T.MEMO,--备注
       T.CREATE_TIME
  FROM SCMDATA.T_ABNORMAL T
  LEFT JOIN DIC DIC1 
    ON DIC1.GROUP_DICT_TYPE = 'ANOMALY_CLASSIFICATION_DICT'
   AND T.ANOMALY_CLASS = DIC1.GROUP_DICT_VALUE 
  LEFT JOIN DIC DIC2  
    ON DIC2.GROUP_DICT_TYPE = 'HANDLE_RESULT'
   AND DIC2.GROUP_DICT_VALUE = T.PROGRESS_STATUS
  LEFT JOIN DIC DIC3
    ON DIC3.GROUP_DICT_TYPE = 'DEDUCTION_METHOD'
   AND DIC3.GROUP_DICT_VALUE = T.HANDLE_OPINIONS
  LEFT JOIN SCMDATA.SYS_COMPANY_DEPT DEPT
    ON T.RESPONSIBLE_DEPT = DEPT.COMPANY_DEPT_ID
   AND T.COMPANY_ID = DEPT.COMPANY_ID
 WHERE T.COMPANY_ID = %DEFAULT_COMPANY_ID%
   AND T.ANOMALY_CLASS = 'AC_QUALITY'
   AND EXISTS (SELECT 1
                 FROM SCMDATA.T_ASNORDERS
                WHERE ASN_ID = :ASN_ID
                  AND COMPANY_ID = T.COMPANY_ID
                  AND GOO_ID = T.GOO_ID)
 ORDER BY T.CREATE_TIME DESC^';
BEGIN
  UPDATE BW3.SYS_ITEM_LIST 
     SET SELECT_SQL = V_SELSQL 
   WHERE ITEM_ID = 'a_qa_102_3';
END;
/
