ALTER TABLE T_PRODUCTION_PROGRESS ADD CURLINK_COMPLET_RATIO        NUMBER;
ALTER TABLE T_PRODUCTION_PROGRESS ADD PROGRESS_UPDATE_DATE         DATE;
ALTER TABLE T_PRODUCTION_PROGRESS ADD ORDER_RISE_STATUS            VARCHAR2(32);
ALTER TABLE T_PRODUCTION_PROGRESS ADD PLAN_DELIVERY_DATE           DATE;
COMMENT ON COLUMN T_PRODUCTION_PROGRESS.CURLINK_COMPLET_RATIO
  IS '当前环节完成比例';
COMMENT ON COLUMN T_PRODUCTION_PROGRESS.PROGRESS_UPDATE_DATE
  IS '进度更新日期';
COMMENT ON COLUMN T_PRODUCTION_PROGRESS.ORDER_RISE_STATUS
  IS '订单风险状态';
COMMENT ON COLUMN T_PRODUCTION_PROGRESS.PLAN_DELIVERY_DATE
  IS '计划到仓日期';
ALTER TABLE T_PROGRESS_NODE_CONFIG ADD PROGRESS_NODE_DESC           VARCHAR2(100);
COMMENT ON COLUMN T_PROGRESS_NODE_CONFIG.PROGRESS_NODE_DESC
  IS '节点名称';

ALTER TABLE t_ordered ADD update_company_id  VARCHAR2(32);
comment on column T_ORDERED.update_company_id
  is '修改方企业';
