BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_check_102''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_APPLY_FORM]'',q''[已审核]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',,q''[list]'',q''[APPLY_FORM_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_check_102''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_APPLY_FORM]'',q''[已审核]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_check_102'',q''[list]'',q''[APPLY_FORM_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_131''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[合作申请详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_131''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[合作申请详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_131'',q''[single]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_210''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[我的申请记录]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_210''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[我的申请记录]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_210'',q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_check_102_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_REPORT]'',q''[验厂报告详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[msingle]'',q''[FACTORY_REPORT_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_check_102_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_REPORT]'',q''[验厂报告详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_check_102_1'',q''[msingle]'',q''[FACTORY_REPORT_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_131_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[合作意向范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_131_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[合作意向范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_131_2'',q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_211''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[SCMDATA.T_FACTORY_ASK]'',q''[查看验厂申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_211]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_211''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[SCMDATA.T_FACTORY_ASK]'',q''[查看验厂申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_211'',q''[single]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_211]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[/* select count(a.factory_ask_id) from t_factory_ask a
  where a.company_id = %default_company_id% and a.factrory_ask_flow_status = 'FA02'*/]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_220''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[待审核申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_220''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[待审核申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_220'',q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_check_102_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[SYS_COMPANY]'',q''[查看企业详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[COMPANY_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_check_102_3]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_check_102_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[SYS_COMPANY]'',q''[查看企业详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_check_102_3'',q''[single]'',q''[COMPANY_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_check_102_3]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_132_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_ASK_RECORD]'',q''[重新申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[msingle]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_132_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_ASK_RECORD]'',q''[重新申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_132_1'',q''[msingle]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_221''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[验厂申请详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_221''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[验厂申请详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_221'',q''[single]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_check_103''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_APPLY_FORM]'',q''[待审核]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[APPLY_FORM_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_check_103''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_APPLY_FORM]'',q''[待审核]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_check_103'',q''[list]'',q''[APPLY_FORM_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_132_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[合作意向范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_132_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[合作意向范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_132_2'',q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_221_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[意向合作范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_221_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[意向合作范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_221_1'',q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_100''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[合作管理]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[menu]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_100''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[合作管理]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_100'',q''[menu]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_133''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[流程操作记录]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',7,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_133''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[流程操作记录]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_133'',q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',7,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_230''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[已审核申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_230''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[已审核申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_230'',q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_102''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[合作申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[manylist]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',4,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_102''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[合作申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_102'',q''[manylist]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',4,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_133_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[流程操作记录]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',7,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_133_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[流程操作记录]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_133_1'',q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',7,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_310''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[待审批申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[action_a_coop_220_10]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_310''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[待审批申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_310'',q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[action_a_coop_220_10]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_103''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[企业详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_103''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[企业详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_103'',q''[single]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_150''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_ASK_RECORD]'',q''[意向合作供应商清单]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_150]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_150''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_ASK_RECORD]'',q''[意向合作供应商清单]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_150'',q''[list]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_150]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_311''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[验厂申请详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_311''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[验厂申请详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_311'',q''[single]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_103_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[企业详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_103_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[企业详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_103_1'',q''[single]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[SYS_COMPANY]'',q''[查看公司档案]'',q''[]'',q''[oracle_scmdata]'',,q''[]'',q''[]'',,q''[single]'',q''[ASK_COMPANY_NAME]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_150_0]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[SYS_COMPANY]'',q''[查看公司档案]'',q''[]'',q''[oracle_scmdata]'',,q''[]'',q''[]'',,''a_coop_150_0'',q''[single]'',q''[ASK_COMPANY_NAME]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_150_0]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_320''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[已审批申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_320''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[已审批申请]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_320'',q''[list]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_104''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[验厂申请详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_104''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[验厂申请详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_104'',q''[single]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_150_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[申请验厂]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[msingle]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_150_3]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_150_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[申请验厂]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_150_3'',q''[msingle]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_150_3]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''test_fl_new_list''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[测试-列表展示新]'',q''[]'',q''[oracle_scmdata]'',,q''[]'',q''[]'',,q''[tabulation]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''test_fl_new_list''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[测试-列表展示新]'',q''[]'',q''[oracle_scmdata]'',,q''[]'',q''[]'',,''test_fl_new_list'',q''[tabulation]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_104_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[意向合作范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_104_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[意向合作范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_104_1'',q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_150_6''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[查看详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_150_6]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_150_6''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[查看详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_150_6'',q''[single]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_150_6]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_105''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_ASK]'',q''[验厂报告详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[msingle]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_105''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_ASK]'',q''[验厂报告详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_105'',q''[msingle]'',q''[FACTORY_ASK_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_151''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_ASK_RECORD]'',q''[新增意向供应商]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_151]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_151''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_ASK_RECORD]'',q''[新增意向供应商]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_151'',q''[single]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_151]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_106''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[流程操作详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',7,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_106''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[流程操作详情]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_106'',q''[list]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',7,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_159''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_ASK_SCOPE]'',q''[意向合作范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[ASK_SCOPE_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_159]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_159''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_ASK_SCOPE]'',q''[意向合作范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_159'',q''[list]'',q''[ASK_SCOPE_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_159]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_check_101''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_APPLY_FORM]'',q''[待验厂]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[APPLY_FORM_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_check_101''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_APPLY_FORM]'',q''[待验厂]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_check_101'',q''[list]'',q''[APPLY_FORM_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_110''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[SYS_COMPANY]'',q''[找客户]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[tabulation]'',q''[COMPANY_ID]'',q''[]'',q''[]'',q''[COMPANY_ID]'',,q''[]'',0,q''[]'',q''[]'',4,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_110''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[SYS_COMPANY]'',q''[找客户]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_110'',q''[tabulation]'',q''[COMPANY_ID]'',q''[]'',q''[]'',q''[COMPANY_ID]'',,q''[]'',0,q''[]'',q''[]'',4,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_159_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_ASK_SCOPE]'',q''[意向合作范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[ASK_SCOPE_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_159_1]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_159_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_ASK_SCOPE]'',q''[意向合作范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_159_1'',q''[list]'',q''[ASK_SCOPE_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_coop_159_1]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_check_101_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_REPORT]'',q''[添加验厂报告]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[msingle]'',q''[FACTORY_REPORT_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_check_101_1]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_check_101_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_REPORT]'',q''[添加验厂报告]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_check_101_1'',q''[msingle]'',q''[FACTORY_REPORT_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_check_101_1]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_120''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[t_supplier_type]'',q''[合作类型选择]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[SUPPLIER_TYPE_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',7,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_120''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[t_supplier_type]'',q''[合作类型选择]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_120'',q''[list]'',q''[SUPPLIER_TYPE_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',7,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_159_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_ASK_SCOPE]'',q''[意向合作范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[ASK_SCOPE_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_159_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_ASK_SCOPE]'',q''[意向合作范围]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_159_2'',q''[list]'',q''[ASK_SCOPE_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_check_101_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_REPORT_ABILITY]'',q''[能力评估]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[FACTORY_REPORT_ABILITY_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_check_101_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_REPORT_ABILITY]'',q''[能力评估]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_check_101_3'',q''[list]'',q''[FACTORY_REPORT_ABILITY_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_121''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_ASK_RECORD]'',q''[合作申请-成品供应商]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[msingle]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_121''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_ASK_RECORD]'',q''[合作申请-成品供应商]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_121'',q''[msingle]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_200''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[]'',q''[验厂申请]'',q''[]'',q''[]'',1,q''[]'',q''[]'',,q''[manylist]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_200''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[]'',q''[验厂申请]'',q''[]'',q''[]'',1,q''[]'',q''[]'',,''a_coop_200'',q''[manylist]'',q''[]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_check_101_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_FACTORY_REPORT]'',q''[附件资料]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[single]'',q''[FACTORY_REPORT_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_check_101_4]'',,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_check_101_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_FACTORY_REPORT]'',q''[附件资料]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_check_101_4'',q''[single]'',q''[FACTORY_REPORT_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[a_check_101_4]'',,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM WHERE ITEM_ID = ''a_coop_130''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM SET (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) = (SELECT ,q''[T_ASK_RECORD]'',q''[我的申请记录]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,q''[list]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',4,q''[]'',q''[]'',,:CV1 FROM DUAL) WHERE ITEM_ID = ''a_coop_130''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM (BADGE_FLAG,BASE_TABLE,CAPTION_SQL,CONFIG_PARAMS,DATA_SOURCE,ENABLE_STAND_PERMISSION,FIX_CAPTION,HELP_ID,INIT_SHOW,ITEM_ID,ITEM_TYPE,KEY_FIELD,LINK_FIELD,MEMO,NAME_FIELD,OFFLINE_FLAG,PANEL_ID,PAUSE,REPORT_TITLE,SETTING_ID,SHOW_ROWID,SUB_SCRIPTS,TAG_ID,TIME_OUT,BADGE_SQL) SELECT ,q''[T_ASK_RECORD]'',q''[我的申请记录]'',q''[]'',q''[oracle_scmdata]'',1,q''[]'',q''[]'',,''a_coop_130'',q''[list]'',q''[ASK_RECORD_ID]'',q''[]'',q''[]'',q''[]'',,q''[]'',0,q''[]'',q''[]'',4,q''[]'',q''[]'',,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

