BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_104'' AND NODE_ID = ''node_a_coop_311_320''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_320]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_104'' AND NODE_ID = ''node_a_coop_311_320''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_104'',''node_a_coop_311_320'',1,q''[a_coop_320]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_221'' AND NODE_ID = ''node_a_coop_221''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_221'' AND NODE_ID = ''node_a_coop_221''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_221'',''node_a_coop_221'',1,q''[]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_check_103'' AND NODE_ID = ''node_a_check_103''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,3,,0,q''[tree_a_check_1]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_check_103'' AND NODE_ID = ''node_a_check_103''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_check_103'',''node_a_check_103'',1,q''[]'',0,3,,0,q''[tree_a_check_1]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''test_fl_new_list'' AND NODE_ID = ''node_test_fl_new_list''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[test_fastlion]'',0,2,,,q''[tree_test]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''test_fl_new_list'' AND NODE_ID = ''node_test_fl_new_list''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''test_fl_new_list'',''node_test_fl_new_list'',1,q''[test_fastlion]'',0,2,,,q''[tree_test]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_120'' AND NODE_ID = ''node_a_coop_120''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_120'' AND NODE_ID = ''node_a_coop_120''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_120'',''node_a_coop_120'',1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_121'' AND NODE_ID = ''node_a_coop_121''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_120]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_121'' AND NODE_ID = ''node_a_coop_121''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_121'',''node_a_coop_121'',1,q''[a_coop_120]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_159'' AND NODE_ID = ''node_a_coop_159''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_159'' AND NODE_ID = ''node_a_coop_159''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_159'',''node_a_coop_159'',1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_102'' AND NODE_ID = ''node_a_coop_102''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_100]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_102'' AND NODE_ID = ''node_a_coop_102''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_102'',''node_a_coop_102'',1,q''[a_coop_100]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_131'' AND NODE_ID = ''node_a_coop_131''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_131'' AND NODE_ID = ''node_a_coop_131''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_131'',''node_a_coop_131'',1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_200'' AND NODE_ID = ''node_a_coop_200''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_coop_100]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_200'' AND NODE_ID = ''node_a_coop_200''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_200'',''node_a_coop_200'',1,q''[a_coop_100]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_210'' AND NODE_ID = ''node_a_coop_210''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_200]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_210'' AND NODE_ID = ''node_a_coop_210''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_210'',''node_a_coop_210'',1,q''[a_coop_200]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_220'' AND NODE_ID = ''node_a_coop_220''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_200]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_220'' AND NODE_ID = ''node_a_coop_220''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_220'',''node_a_coop_220'',1,q''[a_coop_200]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_103'' AND NODE_ID = ''node_a_coop_103''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,5,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_103'' AND NODE_ID = ''node_a_coop_103''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_103'',''node_a_coop_103'',1,q''[]'',0,5,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_104'' AND NODE_ID = ''node_a_coop_104''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,6,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_104'' AND NODE_ID = ''node_a_coop_104''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_104'',''node_a_coop_104'',1,q''[]'',0,6,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_201'' AND NODE_ID = ''node_a_coop_201''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_201'' AND NODE_ID = ''node_a_coop_201''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_201'',''node_a_coop_201'',1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_310'' AND NODE_ID = ''node_a_coop_310''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_coop_300]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_310'' AND NODE_ID = ''node_a_coop_310''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_310'',''node_a_coop_310'',1,q''[a_coop_300]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_311'' AND NODE_ID = ''node_a_coop_311''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_310]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_311'' AND NODE_ID = ''node_a_coop_311''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_311'',''node_a_coop_311'',1,q''[a_coop_310]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_151'' AND NODE_ID = ''node_a_coop_151''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_151'' AND NODE_ID = ''node_a_coop_151''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_151'',''node_a_coop_151'',1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_105'' AND NODE_ID = ''node_a_coop_105''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[]'',0,7,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_105'' AND NODE_ID = ''node_a_coop_105''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_105'',''node_a_coop_105'',1,q''[]'',0,7,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_105'' AND NODE_ID = ''node_a_coop_312_320''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_320]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_105'' AND NODE_ID = ''node_a_coop_312_320''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_105'',''node_a_coop_312_320'',1,q''[a_coop_320]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_320'' AND NODE_ID = ''node_a_coop_320''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_coop_300]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_320'' AND NODE_ID = ''node_a_coop_320''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_320'',''node_a_coop_320'',1,q''[a_coop_300]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150_6'' AND NODE_ID = ''node_a_coop_150_6''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150_6'' AND NODE_ID = ''node_a_coop_150_6''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_150_6'',''node_a_coop_150_6'',1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_check_102'' AND NODE_ID = ''node_a_check_102''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,2,,0,q''[tree_a_check]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_check_102'' AND NODE_ID = ''node_a_check_102''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_check_102'',''node_a_check_102'',1,q''[]'',0,2,,0,q''[tree_a_check]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_check_102_1'' AND NODE_ID = ''node_a_check_102_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_coop_310]'',0,6,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_check_102_1'' AND NODE_ID = ''node_a_check_102_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_check_102_1'',''node_a_check_102_1'',1,q''[a_coop_310]'',0,6,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_100'' AND NODE_ID = ''node_a_coop_100''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[icon-renliziyuanxinxiguanlixitong (275)]'',1,0,1,q''[menuroot]'',0,6,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_100'' AND NODE_ID = ''node_a_coop_100''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[icon-renliziyuanxinxiguanlixitong (275)]'',1,0,''a_coop_100'',''node_a_coop_100'',1,q''[menuroot]'',0,6,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_230'' AND NODE_ID = ''node_a_coop_230''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_200]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_230'' AND NODE_ID = ''node_a_coop_230''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_230'',''node_a_coop_230'',1,q''[a_coop_200]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_132_1'' AND NODE_ID = ''node_a_coop_132_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_132_1'' AND NODE_ID = ''node_a_coop_132_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_132_1'',''node_a_coop_132_1'',1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_check_101'' AND NODE_ID = ''node_a_check_101''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,1,,0,q''[tree_a_check_1]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_check_101'' AND NODE_ID = ''node_a_check_101''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_check_101'',''node_a_check_101'',1,q''[]'',0,1,,0,q''[tree_a_check_1]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_check_101_1'' AND NODE_ID = ''node_a_check_101_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,6,,0,q''[tree_a_check]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_check_101_1'' AND NODE_ID = ''node_a_check_101_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_check_101_1'',''node_a_check_101_1'',1,q''[]'',0,6,,0,q''[tree_a_check]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_103_1'' AND NODE_ID = ''node_a_coop_103_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_103_1'' AND NODE_ID = ''node_a_coop_103_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_103_1'',''node_a_coop_103_1'',1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150_4'' AND NODE_ID = ''node_a_coop_150_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150_4'' AND NODE_ID = ''node_a_coop_150_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_150_4'',''node_a_coop_150_4'',1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150'' AND NODE_ID = ''node_a_coop_150''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_coop_200]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150'' AND NODE_ID = ''node_a_coop_150''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_150'',''node_a_coop_150'',1,q''[a_coop_200]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150_0'' AND NODE_ID = ''node_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150_0'' AND NODE_ID = ''node_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_150_0'',''node_a_coop_150_0'',1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_check_102_3'' AND NODE_ID = ''node_a_check_102_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,0,q''[tree_check]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_check_102_3'' AND NODE_ID = ''node_a_check_102_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_check_102_3'',''node_a_check_102_3'',1,q''[]'',0,1,,0,q''[tree_check]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150_3'' AND NODE_ID = ''node_a_coop_150_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150_3'' AND NODE_ID = ''node_a_coop_150_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_150_3'',''node_a_coop_150_3'',1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_check_101_3'' AND NODE_ID = ''node_a_check_101_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,0,q''[tree_check]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_check_101_3'' AND NODE_ID = ''node_a_check_101_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_check_101_3'',''node_a_check_101_3'',1,q''[]'',0,1,,0,q''[tree_check]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_159_1'' AND NODE_ID = ''node_a_coop_159_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_159_1'' AND NODE_ID = ''node_a_coop_159_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_159_1'',''node_a_coop_159_1'',1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_211'' AND NODE_ID = ''node_a_coop_211''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_211'' AND NODE_ID = ''node_a_coop_211''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_211'',''node_a_coop_211'',1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_159_2'' AND NODE_ID = ''node_a_coop_159_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_159_2'' AND NODE_ID = ''node_a_coop_159_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_159_2'',''node_a_coop_159_2'',1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

