BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_prematerial_210'' AND NODE_ID = ''node_a_prematerial_210''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_prematerial_102]'',0,2,,,q''[tree_a_prematerial]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_prematerial_210'' AND NODE_ID = ''node_a_prematerial_210''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_prematerial_210'',''node_a_prematerial_210'',1,q''[a_prematerial_102]'',0,2,,,q''[tree_a_prematerial]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_prematerial_220'' AND NODE_ID = ''node_a_prematerial_220''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_prematerial_102]'',0,1,,,q''[tree_a_prematerial]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_prematerial_220'' AND NODE_ID = ''node_a_prematerial_220''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_prematerial_220'',''node_a_prematerial_220'',1,q''[a_prematerial_102]'',0,1,,,q''[tree_a_prematerial]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_prematerial_102'' AND NODE_ID = ''node_a_prematerial_102''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_prematerial_100]'',0,1,,,q''[tree_a_prematerial]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_prematerial_102'' AND NODE_ID = ''node_a_prematerial_102''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_prematerial_102'',''node_a_prematerial_102'',1,q''[a_prematerial_100]'',0,1,,,q''[tree_a_prematerial]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_prematerial_240'' AND NODE_ID = ''node_a_prematerial_240''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_prematerial_102]'',0,1,,,q''[tree_a_prematerial]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_prematerial_240'' AND NODE_ID = ''node_a_prematerial_240''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_prematerial_240'',''node_a_prematerial_240'',1,q''[a_prematerial_102]'',0,1,,,q''[tree_a_prematerial]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_prematerial_230'' AND NODE_ID = ''node_a_prematerial_230''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_prematerial_102]'',0,2,,,q''[tree_a_prematerial]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_prematerial_230'' AND NODE_ID = ''node_a_prematerial_230''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_prematerial_230'',''node_a_prematerial_230'',1,q''[a_prematerial_102]'',0,2,,,q''[tree_a_prematerial]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

