BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_241_1_3'' AND ITEM_ID = ''a_prematerial_241_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,3 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_241_1_3'' AND ITEM_ID = ''a_prematerial_241_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_241_1_3'',''a_prematerial_241_1'',,0,3 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_242_2'' AND ITEM_ID = ''a_prematerial_242''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,2 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_242_2'' AND ITEM_ID = ''a_prematerial_242''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_242_2'',''a_prematerial_242'',,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_242_1'' AND ITEM_ID = ''a_prematerial_242''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_242_1'' AND ITEM_ID = ''a_prematerial_242''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_242_1'',''a_prematerial_242'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_242_1'' AND ITEM_ID = ''a_prematerial_242''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_242_1'' AND ITEM_ID = ''a_prematerial_242''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_242_1'',''a_prematerial_242'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_222_2'' AND ITEM_ID = ''a_prematerial_222''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,2 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_222_2'' AND ITEM_ID = ''a_prematerial_222''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_222_2'',''a_prematerial_222'',,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_241_1_4'' AND ITEM_ID = ''a_prematerial_241_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,4 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_241_1_4'' AND ITEM_ID = ''a_prematerial_241_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_241_1_4'',''a_prematerial_241_1'',,0,4 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_1'' AND ITEM_ID = ''a_prematerial_211_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_1'' AND ITEM_ID = ''a_prematerial_211_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_1'',''a_prematerial_211_1'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_230_2'' AND ITEM_ID = ''a_prematerial_231_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,4 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_230_2'' AND ITEM_ID = ''a_prematerial_231_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_230_2'',''a_prematerial_231_1'',,0,4 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_231_1'' AND ITEM_ID = ''a_prematerial_231''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_231_1'' AND ITEM_ID = ''a_prematerial_231''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_231_1'',''a_prematerial_231'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_242_1_1'' AND ITEM_ID = ''a_prematerial_242_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_242_1_1'' AND ITEM_ID = ''a_prematerial_242_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_242_1_1'',''a_prematerial_242_1'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_4'' AND ITEM_ID = ''a_prematerial_212_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,2 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_4'' AND ITEM_ID = ''a_prematerial_212_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_4'',''a_prematerial_212_1'',,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_6'' AND ITEM_ID = ''a_prematerial_212''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,2 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_6'' AND ITEM_ID = ''a_prematerial_212''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_6'',''a_prematerial_212'',,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_2'' AND ITEM_ID = ''a_prematerial_211_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,4 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_2'' AND ITEM_ID = ''a_prematerial_211_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_2'',''a_prematerial_211_1'',,0,4 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_5'' AND ITEM_ID = ''a_prematerial_212''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_5'' AND ITEM_ID = ''a_prematerial_212''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_5'',''a_prematerial_212'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_221_1_3'' AND ITEM_ID = ''a_prematerial_221_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,3 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_221_1_3'' AND ITEM_ID = ''a_prematerial_221_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_221_1_3'',''a_prematerial_221_1'',,0,3 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_230_1'' AND ITEM_ID = ''a_prematerial_231_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_230_1'' AND ITEM_ID = ''a_prematerial_231_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_230_1'',''a_prematerial_231_1'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_221_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,1,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_221_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_221_1'',,1,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_222_1_1'' AND ITEM_ID = ''a_prematerial_222_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_222_1_1'' AND ITEM_ID = ''a_prematerial_222_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_222_1_1'',''a_prematerial_222_1'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_3'' AND ITEM_ID = ''a_prematerial_211_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_3'' AND ITEM_ID = ''a_prematerial_211_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_3'',''a_prematerial_211_1'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_225''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_225''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_225'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_245''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_245''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_245'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_7'' AND ITEM_ID = ''a_prematerial_215''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_7'' AND ITEM_ID = ''a_prematerial_215''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_7'',''a_prematerial_215'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_7'' AND ITEM_ID = ''a_prematerial_235''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_7'' AND ITEM_ID = ''a_prematerial_235''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_7'',''a_prematerial_235'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_222_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,1,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_222_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_222_1'',,1,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_241_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,1,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_241_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_241_1'',,1,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_4'' AND ITEM_ID = ''a_prematerial_211_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,2 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_4'' AND ITEM_ID = ''a_prematerial_211_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_4'',''a_prematerial_211_1'',,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_221_1_1'' AND ITEM_ID = ''a_prematerial_221_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_221_1_1'' AND ITEM_ID = ''a_prematerial_221_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_221_1_1'',''a_prematerial_221_1'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_242_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,1,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_242_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_242_1'',,1,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_244_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,1,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_244_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_244_1'',,1,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_221_1_4'' AND ITEM_ID = ''a_prematerial_221_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,4 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_221_1_4'' AND ITEM_ID = ''a_prematerial_221_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_221_1_4'',''a_prematerial_221_1'',,0,4 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_230_3'' AND ITEM_ID = ''a_prematerial_231_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_230_3'' AND ITEM_ID = ''a_prematerial_231_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_230_3'',''a_prematerial_231_1'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_224_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,1,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_224_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_224_1'',,1,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_243_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,1,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_243_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_243_1'',,1,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_230_4'' AND ITEM_ID = ''a_prematerial_232_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,2 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_230_4'' AND ITEM_ID = ''a_prematerial_232_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_230_4'',''a_prematerial_232_1'',,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_230_5'' AND ITEM_ID = ''a_prematerial_232''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_230_5'' AND ITEM_ID = ''a_prematerial_232''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_230_5'',''a_prematerial_232'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_223_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,1,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_223_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_223_1'',,1,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_223_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,1,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_223_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_221_1'',''a_prematerial_223_1'',,1,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_222_1'' AND ITEM_ID = ''a_prematerial_222''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_222_1'' AND ITEM_ID = ''a_prematerial_222''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_222_1'',''a_prematerial_222'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_7'' AND ITEM_ID = ''a_prematerial_225''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_7'' AND ITEM_ID = ''a_prematerial_225''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_7'',''a_prematerial_225'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_211_1'' AND ITEM_ID = ''a_prematerial_211''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_211_1'' AND ITEM_ID = ''a_prematerial_211''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_211_1'',''a_prematerial_211'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_221''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_221_1'' AND ITEM_ID = ''a_prematerial_221''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_221_1'',''a_prematerial_221'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_230_4'' AND ITEM_ID = ''a_prematerial_231_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,2 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_230_4'' AND ITEM_ID = ''a_prematerial_231_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_230_4'',''a_prematerial_231_1'',,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_221_1_2'' AND ITEM_ID = ''a_prematerial_221_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,2 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_221_1_2'' AND ITEM_ID = ''a_prematerial_221_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_221_1_2'',''a_prematerial_221_1'',,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_230_6'' AND ITEM_ID = ''a_prematerial_232''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,2 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_230_6'' AND ITEM_ID = ''a_prematerial_232''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_230_6'',''a_prematerial_232'',,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_210_2'' AND ITEM_ID = ''a_prematerial_225''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_210_2'' AND ITEM_ID = ''a_prematerial_225''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_210_2'',''a_prematerial_225'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_210_2'' AND ITEM_ID = ''a_prematerial_235''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_210_2'' AND ITEM_ID = ''a_prematerial_235''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_210_2'',''a_prematerial_235'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_241_1'' AND ITEM_ID = ''a_prematerial_241''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_241_1'' AND ITEM_ID = ''a_prematerial_241''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_241_1'',''a_prematerial_241'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_241_1_2'' AND ITEM_ID = ''a_prematerial_241_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,2 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_241_1_2'' AND ITEM_ID = ''a_prematerial_241_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_241_1_2'',''a_prematerial_241_1'',,0,2 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_210_7'' AND ITEM_ID = ''a_prematerial_245''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_210_7'' AND ITEM_ID = ''a_prematerial_245''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_210_7'',''a_prematerial_245'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''action_a_prematerial_241_1_1'' AND ITEM_ID = ''a_prematerial_241_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''action_a_prematerial_241_1_1'' AND ITEM_ID = ''a_prematerial_241_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''action_a_prematerial_241_1_1'',''a_prematerial_241_1'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_210_2'' AND ITEM_ID = ''a_prematerial_215''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_210_2'' AND ITEM_ID = ''a_prematerial_215''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_210_2'',''a_prematerial_215'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ITEM_ELEMENT_RELA WHERE  ELEMENT_ID = ''look_a_prematerial_210_2'' AND ITEM_ID = ''a_prematerial_215''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ITEM_ELEMENT_RELA SET (LEVEL_NO,PAUSE,SEQ_NO) = (SELECT ,0,1 FROM DUAL) WHERE  ELEMENT_ID = ''look_a_prematerial_210_2'' AND ITEM_ID = ''a_prematerial_215''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ITEM_ELEMENT_RELA (ELEMENT_ID,ITEM_ID,LEVEL_NO,PAUSE,SEQ_NO) SELECT ''look_a_prematerial_210_2'',''a_prematerial_215'',,0,1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

