--报价优化
DECLARE
  V_SQL CLOB;
BEGIN
  V_SQL :='{
DECLARE
  V_SQL CLOB;

BEGIN
IF :AC_TEMP_ID IS NOT NULL THEN
  V_SQL:=''SELECT UNIT||''''/元'''' UNIT FROM (
SELECT T.EXTEND_02,  T.EXTEND_03, T.EXTEND_04, T.EXTEND_05, T.EXTEND_06, T.EXTEND_07, T.EXTEND_08
  FROM SCMDATA.SYS_COMPANY_DICT t WHERE t.company_dict_value=''''MRP_MATERIAL_CLASSIFICATION00010019''''
  AND t.company_id=''''b6cc680ad0f599cde0531164a8c0337f''''
  AND t.company_dict_type=''''MRP_MATERIAL_CLASSIFICATION0001'''')  UNPIVOT(UNIT FOR UNIT1 IN(EXTEND_02,EXTEND_03,EXTEND_04,EXTEND_05,EXTEND_06,EXTEND_07,EXTEND_08))'';

ELSE
  V_SQL:=''SELECT UNIT||''''/元'''' UNIT FROM (
SELECT T.EXTEND_02,  T.EXTEND_03, T.EXTEND_04, T.EXTEND_05, T.EXTEND_06, T.EXTEND_07, T.EXTEND_08
  FROM SCMDATA.SYS_COMPANY_DICT t WHERE t.company_dict_value=''''MRP_MATERIAL_CLASSIFICATION00010019''''
  AND t.company_id=''''b6cc680ad0f599cde0531164a8c0337f''''
  AND t.company_dict_type=''''MRP_MATERIAL_CLASSIFICATION0001'''')  UNPIVOT(UNIT FOR UNIT1 IN(EXTEND_02,EXTEND_03,EXTEND_04,EXTEND_05,EXTEND_06,EXTEND_07,EXTEND_08))'';

END IF;

@STRRESULT :=V_SQL;

END;
}';
  
  UPDATE BW3.SYS_LOOK_UP T SET T.LOOK_UP_SQL=V_SQL WHERE T.ELEMENT_ID='look_a_outmaterial_110_5';

END;
/

--单价
DECLARE

BEGIN
  UPDATE BW3.SYS_FIELD_LIST T SET T.DEFAULT_VALUE= '辅料' WHERE T.FIELD_NAME = 'QUOTATION_MATERIAL_TYPE';
 UPDATE BW3.SYS_FIELD_LIST S SET S.CHECK_EXPRESS ='^(([1-9]{1}[0-9]{0,2})|([0]{1}))((\.{1}[0-9]{1,4}$)|$)' ,S.CHECK_MESSAGE ='【单价（元）】支持填写3位自然数，小数允许后4位' WHERE S.FIELD_NAME IN ('QUOTATION_UNIT_PRICE','UNIT_PRICE'); 
END;
/
