BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='COMPANY_ID' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('COMPANY_ID','企业编号',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'COMPANY_ID','企业编号',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null from dual) where field_name='COMPANY_ID' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='APPLY_ID' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('APPLY_ID','应用编号',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'APPLY_ID','应用编号',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null from dual) where field_name='APPLY_ID' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='APPLY_NAME' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('APPLY_NAME','应用名称',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'APPLY_NAME','应用名称',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null from dual) where field_name='APPLY_NAME' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='PAUSE' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('PAUSE','禁用',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,'17',null,null,null,0,0,null,null,null,null,'1','0',null,null,null,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'PAUSE','禁用',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,'17',null,null,null,0,0,null,null,null,null,'1','0',null,null,null,null,null,null,null,null,null,null from dual) where field_name='PAUSE' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='GROUP_MSG_NAME' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('GROUP_MSG_NAME','消息类别名称 ',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'GROUP_MSG_NAME','消息类别名称 ',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='GROUP_MSG_NAME' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='CREATE_ID' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('CREATE_ID','创建人',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'CREATE_ID','创建人',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null from dual) where field_name='CREATE_ID' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='CREATE_TIME' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('CREATE_TIME','创建时间',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,'yyyy-MM-dd HH:mm:ss',null,'12',null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'CREATE_TIME','创建时间',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,'yyyy-MM-dd HH:mm:ss',null,'12',null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null from dual) where field_name='CREATE_TIME' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='PHONE' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('PHONE','手机',0,null,null,null,'^((13[0-9])|(14([1]|[4-9]))|(15([0-3]|[5-9]))|(16([2]|[5-7]))|(17([0-3]|[5-8]))|(18[0-9])|(19[1|8|9]))\d{8}$','请输入正确的手机号',0,0,0,null,0,0,11,11,null,null,null,'16',null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'PHONE','手机',0,null,null,null,'^((13[0-9])|(14([1]|[4-9]))|(15([0-3]|[5-9]))|(16([2]|[5-7]))|(17([0-3]|[5-8]))|(18[0-9])|(19[1|8|9]))\d{8}$','请输入正确的手机号',0,0,0,null,0,0,11,11,null,null,null,'16',null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null from dual) where field_name='PHONE' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='COMPANY_USER_NAME' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('COMPANY_USER_NAME','姓名',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'COMPANY_USER_NAME','姓名',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null from dual) where field_name='COMPANY_USER_NAME' ;
   END IF;
 END ;
 END ;
/
 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='RECEIVER' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('RECEIVER','接收人',0,'为空群发在线用户,否则单发(格式xx;xx)',null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'RECEIVER','接收人',0,'为空群发在线用户,否则单发(格式xx;xx)',null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='RECEIVER' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='MESSAGE_INFO' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('MESSAGE_INFO','消息内容',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,'18',null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'MESSAGE_INFO','消息内容',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,'18',null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='MESSAGE_INFO' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='SENDER' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('SENDER','发送人 ',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'SENDER','发送人 ',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='SENDER' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='TITLE' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('TITLE','标题',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'TITLE','标题',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null from dual) where field_name='TITLE' ;
   END IF;
 END ;
 END ;
/


/


 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='BTN_ENABLE_SQL' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('BTN_ENABLE_SQL','是否继续执行',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'BTN_ENABLE_SQL','是否继续执行',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='BTN_ENABLE_SQL' ;
   END IF;
 END ;
 END ;
/
 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='CAPTION' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('CAPTION','标题',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'CAPTION','标题',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='CAPTION' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='TEXT_SQL' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('TEXT_SQL','消息内容(SQL)',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,'18',null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'TEXT_SQL','消息内容(SQL)',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,'18',null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='TEXT_SQL' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='BTN_EXEC_SQL' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('BTN_EXEC_SQL','按钮执行SQL',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,'18',null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'BTN_EXEC_SQL','按钮执行SQL',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,'18',null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='BTN_EXEC_SQL' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='HINT_FLAG' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('HINT_FLAG','提醒方式 ',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'HINT_FLAG','提醒方式 ',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='HINT_FLAG' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='BTN_CAPTION' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('BTN_CAPTION','按钮标题 ',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'BTN_CAPTION','按钮标题 ',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='BTN_CAPTION' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='WRAP_FLAG' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('WRAP_FLAG','是否换行',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'WRAP_FLAG','是否换行',1,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='WRAP_FLAG' ;
   END IF;
 END ;
 END ;
/

 BEGIN 
 DECLARE 
   V_CNT  NUMBER(1); 

 BEGIN 
   SELECT COUNT(*) INTO V_CNT FROM sys_field_list where field_name='NODE_ID' ;
   IF V_CNT=0 THEN   
       insert into sys_field_list(FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)
       values ('NODE_ID','跳转节点',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null);
   ELSE 
       update sys_field_list set (FIELD_NAME,CAPTION,REQUIERED_FLAG,INPUT_HINT,VALID_CHARS,INVALID_CHARS,CHECK_EXPRESS,CHECK_MESSAGE,READ_ONLY_FLAG,NO_EDIT,NO_COPY,NO_SUM,NO_SORT,ALIGNMENT,MAX_LENGTH,MIN_LENGTH,DISPLAY_WIDTH,DISPLAY_FORMAT,EDIT_FORMT,DATA_TYPE,MAX_VALUE,MIN_VALUE,DEFAULT_VALUE,IME_CARE,IME_OPEN,VALUE_LISTS,VALUE_LIST_TYPE,HYPER_RES,MULTI_VALUE_FLAG,TRUE_EXPR,FALSE_EXPR,NAME_RULE_FLAG,NAME_RULE_ID,DATA_TYPE_FLAG,ALLOW_SCAN,VALUE_ENCRYPT,VALUE_SENSITIVE,OPERATOR_FLAG,VALUE_DISPLAY_STYLE,TO_ITEM_ID,VALUE_SENSITIVE_REPLACEMENT)=(select 'NODE_ID','跳转节点',0,null,null,null,null,null,0,0,0,null,0,0,null,null,null,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null from dual) where field_name='NODE_ID' ;
   END IF;
 END ;
 END ;
/

 

