BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_118_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_118_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_118_3'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_118_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_118_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_118_3'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_approve_110''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_approve_110''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_approve_110'',q''[lookup]'',,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_111_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_111_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_111_1'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_118_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_118_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_118_1'',q''[lookup]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_118_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_118_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_118_2'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_118_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_118_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_118_4'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_118_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_118_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_118_4'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_110_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_110_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_110_1'',q''[pick]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_110_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_110_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_110_2'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_110_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',3,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_110_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_110_3'',q''[pick]'',,0,,q''[]'',3,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_118_5''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_118_5''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_118_5'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''associate_a_product_117''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[associate]'',,,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''associate_a_product_117''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''associate_a_product_117'',q''[associate]'',,,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_118_5''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_118_5''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_118_5'',q''[pick]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_120_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_120_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_120_1'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_120_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_120_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_120_2'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''associate_a_product_101''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[associate]'',,1,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''associate_a_product_101''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''associate_a_product_101'',q''[associate]'',,1,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''associate_a_product_101''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[associate]'',,1,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''associate_a_product_101''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''associate_a_product_101'',q''[associate]'',,1,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_130_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_130_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_130_2'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_130_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_130_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_130_1'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''assocaite_a_product_112''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[associate]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''assocaite_a_product_112''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''assocaite_a_product_112'',q''[associate]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''associate_a_product_113''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[associate]'',,1,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''associate_a_product_113''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''associate_a_product_113'',q''[associate]'',,1,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_101_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_101_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_101_4'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_118_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_118_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_118_2'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_118_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_118_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_118_3'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_110_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_110_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_110_1'',q''[action]'',,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_110''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_110''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_110'',q''[action]'',,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_118''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_118''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_118'',q''[action]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_110_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_110_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_110_3'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_118_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_118_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_118_1'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_118_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_118_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_118_1'',q''[lookup]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_110_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_110_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_110_4'',q''[action]'',,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''action_a_product_118_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''action_a_product_118_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''action_a_product_118_4'',q''[action]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_118_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',1,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_118_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_118_1'',q''[lookup]'',,0,,q''[]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_118_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_118_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_118_2'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_118_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_118_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_118_2'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_118_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_118_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_118_3'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_118_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_118_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_118_1'',q''[pick]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_118_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_118_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_118_3'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_110_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_110_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_110_2'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_118_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_118_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_118_1'',q''[pick]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''pick_a_product_118_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[pick]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''pick_a_product_118_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''pick_a_product_118_1'',q''[pick]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_110_2''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_110_2''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_110_2'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_approve_110''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_approve_110''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_approve_110'',q''[lookup]'',,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_product_118_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_product_118_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_product_118_3'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''look_a_product_118_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''look_a_product_118_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''look_a_product_118_4'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''look_a_product_118_5''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''look_a_product_118_5''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''look_a_product_118_5'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''look_a_product_118_5''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''look_a_product_118_5''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''look_a_product_118_5'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''look_a_product_118_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''look_a_product_118_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''look_a_product_118_4'',q''[lookup]'',,0,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT WHERE ELEMENT_ID = ''lookup_a_approve_101_0_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT SET (DATA_SOURCE,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) = (SELECT q''[oracle_scmdata]'',q''[lookup]'',,,,q''[]'',0,:CV1 FROM DUAL) WHERE ELEMENT_ID = ''lookup_a_approve_101_0_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT (DATA_SOURCE,ELEMENT_ID,ELEMENT_TYPE,IS_ASYNC,IS_HIDE,IS_PER_EXE,MEMO,PAUSE,MESSAGE) SELECT q''[oracle_scmdata]'',''lookup_a_approve_101_0_0'',q''[lookup]'',,,,q''[]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

