BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_product_101'' AND ITEM_ID = ''a_product_116''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[GOO_ID_PR]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_product_101'' AND ITEM_ID = ''a_product_116''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_product_101'',,''a_product_116'',q''[]'',q''[GOO_ID_PR]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_product_101'' AND ITEM_ID = ''a_product_110''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[GOO_ID_PR]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_product_101'' AND ITEM_ID = ''a_product_110''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_product_101'',,''a_product_110'',q''[]'',q''[GOO_ID_PR]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'[]';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_product_113'' AND ITEM_ID = ''a_product_113''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[QUALITY_TESTING_RESULT]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_product_113'' AND ITEM_ID = ''a_product_113''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_product_113'',,''a_product_113'',q''[]'',q''[QUALITY_TESTING_RESULT]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

