BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^是否前往“供应商主档导入”页面？^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_OPERATE WHERE COND_ID = ''cond_checkaction_a_supp_160''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_OPERATE SET (CAPTION,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) = (SELECT q''[提示]'',q''[]'',q''[a_supp_160_1]'',:CV1 FROM DUAL) WHERE COND_ID = ''cond_checkaction_a_supp_160''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_OPERATE (CAPTION,COND_ID,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) SELECT q''[提示]'',''cond_checkaction_a_supp_160'',q''[]'',q''[a_supp_160_1]'',:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^是否前往供应商选择界面^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_OPERATE WHERE COND_ID = ''cond_checkaction_a_supp_151_6''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_OPERATE SET (CAPTION,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) = (SELECT q''[提示]'',q''[]'',q''[a_supp_151_4]'',:CV1 FROM DUAL) WHERE COND_ID = ''cond_checkaction_a_supp_151_6''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_OPERATE (CAPTION,COND_ID,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) SELECT q''[提示]'',''cond_checkaction_a_supp_151_6'',q''[]'',q''[a_supp_151_4]'',:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^是否前往供应商档案新增页面？^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_OPERATE WHERE COND_ID = ''cond_a_supp_150_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_OPERATE SET (CAPTION,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) = (SELECT q''[提示]'',q''[]'',q''[a_supp_151]'',:CV1 FROM DUAL) WHERE COND_ID = ''cond_a_supp_150_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_OPERATE (CAPTION,COND_ID,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) SELECT q''[提示]'',''cond_a_supp_150_1'',q''[]'',q''[a_supp_151]'',:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^是否前往“批量导入合同”操作页面？^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_OPERATE WHERE COND_ID = ''cond_checkaction_a_supp_151''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_OPERATE SET (CAPTION,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) = (SELECT q''[提示]'',q''[]'',q''[a_supp_151_6]'',:CV1 FROM DUAL) WHERE COND_ID = ''cond_checkaction_a_supp_151''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_OPERATE (CAPTION,COND_ID,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) SELECT q''[提示]'',''cond_checkaction_a_supp_151'',q''[]'',q''[a_supp_151_6]'',:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^是否前往“供应商合作范围导入”页面？^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_OPERATE WHERE COND_ID = ''cond_action_a_supp_170''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_OPERATE SET (CAPTION,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) = (SELECT q''[提示]'',q''[]'',q''[a_supp_170]'',:CV1 FROM DUAL) WHERE COND_ID = ''cond_action_a_supp_170''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_OPERATE (CAPTION,COND_ID,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) SELECT q''[提示]'',''cond_action_a_supp_170'',q''[]'',q''[a_supp_170]'',:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^提交成功，是否前往“已建档供应商列表”？^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_OPERATE WHERE COND_ID = ''cond_checkaction_a_supp_160_1_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_OPERATE SET (CAPTION,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) = (SELECT q''[提示]'',q''[]'',q''[a_supp_160]'',:CV1 FROM DUAL) WHERE COND_ID = ''cond_checkaction_a_supp_160_1_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_OPERATE (CAPTION,COND_ID,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) SELECT q''[提示]'',''cond_checkaction_a_supp_160_1_3'',q''[]'',q''[a_supp_160]'',:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^已提交，是否跳转到已验厂页面^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_OPERATE WHERE COND_ID = ''cond_a_check_101_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_OPERATE SET (CAPTION,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) = (SELECT q''[跳转提示]'',q''[a_check_101_1]'',q''[a_check_102]'',:CV1 FROM DUAL) WHERE COND_ID = ''cond_a_check_101_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_OPERATE (CAPTION,COND_ID,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) SELECT q''[跳转提示]'',''cond_a_check_101_1'',q''[a_check_101_1]'',q''[a_check_102]'',:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

