BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_RELA WHERE  COND_ID = ''cond_g_530'' AND CTL_ID = ''g_530''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_RELA SET (CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) = (SELECT 0,q''[]'',14,0, FROM DUAL) WHERE  COND_ID = ''cond_g_530'' AND CTL_ID = ''g_530''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_RELA (COND_ID,CTL_ID,CTL_TYPE,ITEM_ID,OBJ_TYPE,PAUSE,SEQ_NO) SELECT ''cond_g_530'',''g_530'',0,q''[]'',14,0, FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

