BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^已提交，是否跳转到已验厂页面^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_COND_OPERATE WHERE COND_ID = ''cond_a_check_101_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_COND_OPERATE SET (CAPTION,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) = (SELECT q''[跳转提示]'',q''[a_check_101_1]'',q''[a_check_102]'',:CV1 FROM DUAL) WHERE COND_ID = ''cond_a_check_101_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_COND_OPERATE (CAPTION,COND_ID,TO_CANCEL_ITEM_ID,TO_CONFIRM_ITEM_ID,CONTENT) SELECT q''[跳转提示]'',''cond_a_check_101_1'',q''[a_check_101_1]'',q''[a_check_102]'',:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

