BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_supp_111_5'' AND NODE_ID = ''node_a_supp_111_5''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[企业档案详情]'',,,q''[]'',1,0,1,q''[]'',0,0,,0,q''[tree_a_supp_1]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_supp_111_5'' AND NODE_ID = ''node_a_supp_111_5''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[企业档案详情]'',,,q''[]'',1,0,''a_supp_111_5'',''node_a_supp_111_5'',1,q''[]'',0,0,,0,q''[tree_a_supp_1]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_159_1'' AND NODE_ID = ''node_a_coop_159_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_159_1'' AND NODE_ID = ''node_a_coop_159_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_159_1'',''node_a_coop_159_1'',1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_supp_160_1'' AND NODE_ID = ''node_a_supp_160_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[供应商导入]'',,,q''[]'',1,0,1,q''[]'',0,1,,0,q''[tree_a_supp_1]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_supp_160_1'' AND NODE_ID = ''node_a_supp_160_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[供应商导入]'',,,q''[]'',1,0,''a_supp_160_1'',''node_a_supp_160_1'',1,q''[]'',0,1,,0,q''[tree_a_supp_1]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_121'' AND NODE_ID = ''node_a_coop_121''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_120]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_121'' AND NODE_ID = ''node_a_coop_121''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_121'',''node_a_coop_121'',1,q''[a_coop_120]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_159'' AND NODE_ID = ''node_a_coop_159''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_159'' AND NODE_ID = ''node_a_coop_159''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_159'',''node_a_coop_159'',1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_200'' AND NODE_ID = ''node_a_coop_200''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[icon-jiexi]'',1,0,1,q''[a_coop_100]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_200'' AND NODE_ID = ''node_a_coop_200''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[icon-jiexi]'',1,0,''a_coop_200'',''node_a_coop_200'',1,q''[a_coop_100]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_210'' AND NODE_ID = ''node_a_coop_210''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_200]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_210'' AND NODE_ID = ''node_a_coop_210''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_210'',''node_a_coop_210'',1,q''[a_coop_200]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_220'' AND NODE_ID = ''node_a_coop_220''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_200]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_220'' AND NODE_ID = ''node_a_coop_220''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_220'',''node_a_coop_220'',1,q''[a_coop_200]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_230'' AND NODE_ID = ''node_a_coop_230''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_200]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_230'' AND NODE_ID = ''node_a_coop_230''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_230'',''node_a_coop_230'',1,q''[a_coop_200]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_201'' AND NODE_ID = ''node_a_coop_201''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_201'' AND NODE_ID = ''node_a_coop_201''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_201'',''node_a_coop_201'',1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150_6'' AND NODE_ID = ''node_a_coop_150_6''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150_6'' AND NODE_ID = ''node_a_coop_150_6''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_150_6'',''node_a_coop_150_6'',1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_103_1'' AND NODE_ID = ''node_a_coop_103_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_103_1'' AND NODE_ID = ''node_a_coop_103_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_103_1'',''node_a_coop_103_1'',1,q''[]'',0,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150_4'' AND NODE_ID = ''node_a_coop_150_4''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150_4'' AND NODE_ID = ''node_a_coop_150_4''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_150_4'',''node_a_coop_150_4'',1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_312'' AND NODE_ID = ''node_a_coop_312''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_310]'',1,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_312'' AND NODE_ID = ''node_a_coop_312''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_312'',''node_a_coop_312'',1,q''[a_coop_310]'',1,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_311'' AND NODE_ID = ''node_a_coop_311''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_310]'',1,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_311'' AND NODE_ID = ''node_a_coop_311''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_311'',''node_a_coop_311'',1,q''[a_coop_310]'',1,1,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_151'' AND NODE_ID = ''node_a_coop_151''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_151'' AND NODE_ID = ''node_a_coop_151''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_151'',''node_a_coop_151'',1,q''[]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_supp_160'' AND NODE_ID = ''node_a_supp_160''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[已建档供应商(新)]'',,,q''[]'',1,0,1,q''[a_supp_000]'',1,5,,0,q''[tree_a_supp]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_supp_160'' AND NODE_ID = ''node_a_supp_160''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[已建档供应商(新)]'',,,q''[]'',1,0,''a_supp_160'',''node_a_supp_160'',1,q''[a_supp_000]'',1,5,,0,q''[tree_a_supp]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_103'' AND NODE_ID = ''node_a_coop_103''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,,1,q''[]'',0,5,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_103'' AND NODE_ID = ''node_a_coop_103''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,,''a_coop_103'',''node_a_coop_103'',1,q''[]'',0,5,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_221'' AND NODE_ID = ''node_a_coop_221''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_221'' AND NODE_ID = ''node_a_coop_221''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_221'',''node_a_coop_221'',1,q''[]'',0,2,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150_3'' AND NODE_ID = ''node_a_coop_320_1''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,1,q''[a_coop_320]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150_3'' AND NODE_ID = ''node_a_coop_320_1''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,1,''a_coop_150_3'',''node_a_coop_320_1'',1,q''[a_coop_320]'',0,3,,,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_supp_120'' AND NODE_ID = ''node_a_supp_120''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[已建档供应商]'',,,q''[]'',1,0,1,q''[a_supp_000]'',1,2,,0,q''[tree_a_supp]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_supp_120'' AND NODE_ID = ''node_a_supp_120''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[已建档供应商]'',,,q''[]'',1,0,''a_supp_120'',''node_a_supp_120'',1,q''[a_supp_000]'',1,2,,0,q''[tree_a_supp]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150'' AND NODE_ID = ''node_a_coop_150''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_coop_200]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150'' AND NODE_ID = ''node_a_coop_150''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_150'',''node_a_coop_150'',1,q''[a_coop_200]'',0,1,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150_0'' AND NODE_ID = ''node_a_coop_150_0''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150_0'' AND NODE_ID = ''node_a_coop_150_0''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_150_0'',''node_a_coop_150_0'',1,q''[]'',0,6,,0,q''[tree_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_supp_151'' AND NODE_ID = ''node_a_supp_151''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[供应商档案详情(新)(未建档)]'',,,q''[]'',1,0,1,q''[]'',0,1,,0,q''[tree_a_supp_1]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_supp_151'' AND NODE_ID = ''node_a_supp_151''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[供应商档案详情(新)(未建档)]'',,,q''[]'',1,0,''a_supp_151'',''node_a_supp_151'',1,q''[]'',0,1,,0,q''[tree_a_supp_1]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_supp_111'' AND NODE_ID = ''node_a_supp_111''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[供应商档案详情(未建档)]'',,,q''[]'',1,0,1,q''[]'',0,1,,0,q''[tree_a_supp_1]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_supp_111'' AND NODE_ID = ''node_a_supp_111''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[供应商档案详情(未建档)]'',,,q''[]'',1,0,''a_supp_111'',''node_a_supp_111'',1,q''[]'',0,1,,0,q''[tree_a_supp_1]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_TREE_LIST WHERE  ITEM_ID = ''a_coop_150_3'' AND NODE_ID = ''node_a_coop_150_3''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_TREE_LIST SET (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) = (SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,1,q''[a_coop_310]'',0,6,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL) WHERE  ITEM_ID = ''a_coop_150_3'' AND NODE_ID = ''node_a_coop_150_3''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_TREE_LIST (APP_ID,CAPTION_EXPLAIN,COMPETENCE_FLAG,ENABLE_STAND_PERMISSION,ICON_NAME,IS_AUTHORIZE,IS_END,ITEM_ID,NODE_ID,NODE_TYPE,PARENT_ID,PAUSE,SEQ_NO,STAND_PRIV_FLAG,TERMINAL_FLAG,TREE_ID,VAR_ID) SELECT q''[scm]'',q''[]'',,,q''[]'',1,0,''a_coop_150_3'',''node_a_coop_150_3'',1,q''[a_coop_310]'',0,6,,0,q''[tree_a_coop]'',q''[]'' FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL;
     END IF;
  END;
END;
/

