BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_coop_103_1_230'' AND ITEM_ID = ''a_coop_230''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[LOGN_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_coop_103_1_230'' AND ITEM_ID = ''a_coop_230''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_coop_103_1_230'',,''a_coop_230'',q''[]'',q''[LOGN_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_supp_120_1'' AND ITEM_ID = ''a_supp_120''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[SUPPLIER_COMPANY_NAME]'',1,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_supp_120_1'' AND ITEM_ID = ''a_supp_120''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_supp_120_1'',,''a_supp_120'',q''[]'',q''[SUPPLIER_COMPANY_NAME]'',1,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_coop_103_130'' AND ITEM_ID = ''a_coop_130''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[BE_ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_coop_103_130'' AND ITEM_ID = ''a_coop_130''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_coop_103_130'',,''a_coop_130'',q''[]'',q''[BE_ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_coop_210''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_coop_210''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_coop_150_0'',,''a_coop_210'',q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_coop_131'' AND ITEM_ID = ''a_coop_130''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[ASK_RECORD_ID]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_coop_131'' AND ITEM_ID = ''a_coop_130''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_coop_131'',,''a_coop_130'',q''[]'',q''[ASK_RECORD_ID]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_coop_220''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_coop_220''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_coop_150_0'',,''a_coop_220'',q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_coop_230''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_coop_230''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_coop_150_0'',,''a_coop_230'',q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_coop_150''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''asso_a_coop_150_0'' AND ITEM_ID = ''a_coop_150''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''asso_a_coop_150_0'',,''a_coop_150'',q''[]'',q''[ASK_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_coop_103_1_220'' AND ITEM_ID = ''a_coop_220''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[LOGN_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_coop_103_1_220'' AND ITEM_ID = ''a_coop_220''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_coop_103_1_220'',,''a_coop_220'',q''[]'',q''[LOGN_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_supp_110_3'' AND ITEM_ID = ''a_supp_160''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[SUPPLIER_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_supp_110_3'' AND ITEM_ID = ''a_supp_160''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_supp_110_3'',,''a_supp_160'',q''[]'',q''[SUPPLIER_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

BEGIN
  DECLARE
    JUDGE_N NUMBER(4);
    EXE_SQL CLOB;
    VALS    CLOB;
  CV1 CLOB:=q'^^';

  BEGIN
    EXE_SQL := 'SELECT COUNT(1) FROM BW3.SYS_ELEMENT_HINT WHERE  ELEMENT_ID = ''associate_a_supp_110_3'' AND ITEM_ID = ''a_supp_120''';
    EXECUTE IMMEDIATE EXE_SQL INTO JUDGE_N;
    IF JUDGE_N > 0 THEN
       EXE_SQL := 'UPDATE BW3.SYS_ELEMENT_HINT SET (HINT_TYPE,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) = (SELECT ,q''[]'',q''[SUPPLIER_COMPANY_NAME]'',0,:CV1 FROM DUAL) WHERE  ELEMENT_ID = ''associate_a_supp_110_3'' AND ITEM_ID = ''a_supp_120''';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     ELSE
       EXE_SQL := 'INSERT INTO BW3.SYS_ELEMENT_HINT (ELEMENT_ID,HINT_TYPE,ITEM_ID,JUDGE_FIELD,LINK_NAME,PAUSE,MESSAGE) SELECT ''associate_a_supp_110_3'',,''a_supp_120'',q''[]'',q''[SUPPLIER_COMPANY_NAME]'',0,:CV1 FROM DUAL';
       WHILE REGEXP_COUNT(EXE_SQL,',,') > 0 LOOP
         EXE_SQL := REPLACE(EXE_SQL,',,',',NULL,');
       END LOOP;
       EXE_SQL := REPLACE(REPLACE(EXE_SQL,'SELECT ,','SELECT NULL,'),', FROM',',NULL FROM');
       EXECUTE IMMEDIATE EXE_SQL USING CV1;
     END IF;
  END;
END;
/

